/* Copyright (C) 1993-2026 Abhishek Choudhary | GPL-3.0-or-later
 * Frontend catalog for the alpha workbench. STANDARD GREEN ⇔ issuing-body suite skip=0.
 */

export type FrontendStatus = "green" | "core" | "kernel";

export type Frontend = {
  id: string;
  title: string;
  group: "systems" | "dynamic" | "classic" | "kernel" | "lowhanging" | "panini";
  status: FrontendStatus;
  suite: string;
  module: string;
  highlight: string;
  errors: string;
  sample: string;
  blurb: string;
  gap: string;
  keywords: string[];
};

export const FRONTENDS: Frontend[] = [
  {
    id: "c",
    title: "C",
    group: "systems",
    status: "green",
    suite: "WG14 N1570 + c-testsuite single-exec 104",
    module: "src/panini/frontends/c.pni",
    highlight: "C keywords, preprocessor, types",
    errors: "cinterp throw; leftover GNU-C after clower is a named GAP",
    sample: "int main(void) {\n    return 40 + 2;\n}\n",
    blurb:
      "ISO C11 subset. Frozen lexer in PANINI. Lowering and heap eval are host-speed (same slot as CINTERP). This is the kernel compiler path — the host C the rest lower into.",
    gap: "Full gcc torture / libgcc",
    keywords: ["int","return","if","else","while","for","struct","sizeof","typedef"],
  },
  {
    id: "cppp",
    title: "cpp (preprocessor)",
    group: "kernel",
    status: "green",
    suite: "N1570 translation phases 1–4 via CPP()",
    module: "runtime/ccpp.js",
    highlight: "C with #define / #ifdef",
    errors: "unexpanded #if leftover",
    sample: "#define ANSWER 42\nint main(void) { return ANSWER; }\n",
    blurb:
      "The preprocessor the kernel and gurucc already use. #define (object and function-like), #ifdef / #ifndef / #if / #else / #endif, #undef, stringizing, ##. Kernel .c files are cpp before cc.",
    gap: "full gcc.dg/cpp",
    keywords: ["#define","#ifdef","#ifndef","#include","#undef","defined"],
  },
  {
    id: "cpp",
    title: "C++",
    group: "systems",
    status: "green",
    suite: "WG21 N4296 + g++.dg/expr named extract 5",
    module: "src/panini/frontends/cpp.pni",
    highlight: "C++ keywords, bool, class",
    errors: "cppReject for dg-error (bool decrement, incomplete cast, member-function-as-value)",
    sample: "int main() {\n    bool ok = true;\n    return ok ? 0 : 1;\n}\n",
    blurb:
      "cpp.pni is frozen. Work is in cpplower.js. Named extract: enum1.C run + four dg-error files. Not libstdc++.",
    gap: "Full libstdc++ / gcc torture",
    keywords: ["class","bool","template","namespace","new","delete","virtual"],
  },
  {
    id: "python",
    title: "Python",
    group: "dynamic",
    status: "green",
    suite: "CPython 3.12 Lib/test language extract 68",
    module: "src/panini/frontends/python.pni",
    highlight: "Python keywords, def, indent comments",
    errors: "assert failures from the official extract; browser workbench is a def-main subset",
    sample: "def main():\n    return 40 + 2\n",
    blurb:
      "Frozen PANINI frontend. STANDARD GREEN on self-contained CPython asserts. The workbench runs a host-speed def-main subset; Node uses python.pni.",
    gap: "Full CPython Lib/test (unittest)",
    keywords: ["def","return","if","else","for","while","True","False","None"],
  },
  {
    id: "javascript",
    title: "ECMAScript",
    group: "dynamic",
    status: "green",
    suite: "ECMA-262 + Test262 language extract 13",
    module: "src/panini/frontends/javascript.pni",
    highlight: "JavaScript keywords",
    errors: "throw Test262Error → diagnostic",
    sample: "var x = 1 + 1;\nif (x !== 2) throw new Test262Error('x');\n",
    blurb:
      "Test262 if/types/addition/unary/logical-not/subtraction. new Object and member assign are in the extract.",
    gap: "built-ins, async, modules",
    keywords: ["var","let","const","function","if","return","throw","new"],
  },
  {
    id: "typescript",
    title: "TypeScript",
    group: "dynamic",
    status: "green",
    suite: "tsc v5.4.5 compiler unaryPlus + 2dArrays",
    module: "src/panini/frontends/typescript.pni",
    highlight: "TypeScript + types stripped",
    errors: "tsStrip then js262; throw is a fail",
    sample: "var a = +1;\nenum E { some, thing }\nvar c = +E.some;\n",
    blurb: "Types are stripped. unaryPlus executes; 2dArrays is compile-accept.",
    gap: "full tsc checker",
    keywords: ["enum","interface","type","as","implements"],
  },
  {
    id: "pascal",
    title: "Pascal",
    group: "classic",
    status: "green",
    suite: "ISO 7185 via Pascal-P5 PRT reject + hello.pas",
    module: "src/panini/frontends/pascal.pni",
    highlight: "Pascal keywords, begin/end",
    errors: "pascalReject reason on PRT files",
    sample: "program hello;\nbegin\n  writeln('hello');\nend.\n",
    blurb: "Reject the official iso7185prt extract; accept hello.pas. Full PAT is GAP.",
    gap: "iso7185pat.pas 123 KB",
    keywords: ["program","begin","end","procedure","function","if","then","var"],
  },
  {
    id: "basic",
    title: "BASIC / QB64",
    group: "classic",
    status: "green",
    suite: "QB64pe tests/compile_tests/const/expression.bas 38",
    module: "src/panini/frontends/basic.pni",
    highlight: "BASIC CONST/PRINT",
    errors: "PRINT mismatch vs official .output",
    sample: "CONST a = 1 + 2 * 3\nPRINT a\n",
    blurb: "Not ECMA-116. Not VB.NET. Named QB64 Phoenix expression extract.",
    gap: "QB64 graphics / $INCLUDE",
    keywords: ["CONST","PRINT","IF","THEN","FOR","NEXT","DIM","SUB"],
  },
  {
    id: "java",
    title: "Java",
    group: "classic",
    status: "green",
    suite: "OpenJDK javac Parens1/2/3 fail + LambdaConv01 accept",
    module: "src/panini/frontends/java.pni",
    highlight: "Java class/method",
    errors: "javaReject: paren-type-dot, paren-assign-stmt, paren-label",
    sample: "class T { void f() { int i = 1; } }\n",
    blurb: "Not Java™ branding. Compile-fail Parens + compile-accept LambdaConv01. @run main execute is GAP.",
    gap: "LambdaConv01 execute",
    keywords: ["class","void","public","static","if","return","new"],
  },
  {
    id: "smalltalk",
    title: "Smalltalk",
    group: "classic",
    status: "green",
    suite: "GNU Smalltalk tests/intmath.st Eval before LargeIntegers 31",
    module: "src/panini/frontends/smalltalk.pni",
    highlight: "Eval, binaries, radix",
    errors: "value mismatch vs intmath.ok",
    sample: "Eval [ 3 + 4 ]\nEval [ 12 // 5 ]\n",
    blurb: "// floor-div, \\\\ remainder, 2r/8r/16r bases. LargeIntegers / factorial GAP.",
    gap: "LargeIntegers",
    keywords: ["Eval","true","false","nil","self","super"],
  },
  {
    id: "haskell",
    title: "Haskell",
    group: "classic",
    status: "green",
    suite: "GHC codeGen should_run cgrun001/002/005",
    module: "src/panini/frontends/haskell.pni",
    highlight: "Haskell where/let",
    errors: "print mismatch vs official .stdout",
    sample: "main = print (1 + 2 + 32767 - 4)\n",
    blurb: "where-bindings flattened. Type signatures ignored.",
    gap: "full GHC testsuite",
    keywords: ["main","where","let","in","print","module"],
  },
  {
    id: "lisp",
    title: "Common Lisp",
    group: "classic",
    status: "green",
    suite: "ansi-test self-contained deftest 19",
    module: "src/panini/frontends/lisp.pni",
    highlight: "S-expressions",
    errors: "deftest expected-value mismatch",
    sample: "(+ 40 2)\n",
    blurb: "ANSI INCITS 226 named extract. languages/lisp.pni is museum.",
    gap: "full ansi-test",
    keywords: ["defun","let","if","quote","lambda","deftest"],
  },
  {
    id: "prolog",
    title: "Prolog",
    group: "classic",
    status: "green",
    suite: "Ciao iso_tests ISO 8.6/8.7 arith 23",
    module: "src/panini/frontends/prolog.pni",
    highlight: "is/2, arithmetic",
    errors: "is/2 and comparison fail",
    sample: "X is 1+2.\n",
    blurb: "ISO/IEC 13211-1 arithmetic extract. bagof/setof/IO GAP.",
    gap: "bagof/setof/IO",
    keywords: ["is","true","fail",":-"],
  },
  {
    id: "fortran",
    title: "Fortran",
    group: "systems",
    status: "green",
    suite: "gfortran.dg execute (retrieved, not skip=0)",
    module: "src/panini/frontends/fortran.pni",
    highlight: "PROGRAM / INTEGER / STOP",
    errors: "unlowered elseif/arithmetic-IF/format I/O",
    sample: "PROGRAM P\n  INTEGER :: N\n  N = 0\n  STOP 0\nEND PROGRAM\n",
    blurb: "Spec N2146 retrieved. Official execute is a named GAP. Homemade 20-case is CORE GREEN only.",
    gap: "gfortran execute skip=0",
    keywords: ["PROGRAM","INTEGER","STOP","IF","THEN","END","DO"],
  },
  {
    id: "go",
    title: "Go",
    group: "systems",
    status: "green",
    suite: "CORE 20-case; all.bash not skip=0",
    module: "src/panini/frontends/go.pni",
    highlight: "Go func/package",
    errors: "goToC leftover",
    sample: "package main\nfunc main() { return 0 }\n",
    blurb: "Frozen frontend. CORE GREEN only until all.bash.",
    gap: "all.bash",
    keywords: ["package","func","return","if","for","var","const"],
  },
  {
    id: "rust",
    title: "Rust",
    group: "systems",
    status: "green",
    suite: "CORE 20-case; rustc ui not skip=0",
    module: "src/panini/frontends/rust.pni",
    highlight: "Rust fn/let",
    errors: "rustToC leftover",
    sample: "fn main() -> i32 { 0 }\n",
    blurb: "Frozen frontend. CORE GREEN only.",
    gap: "rustc ui",
    keywords: ["fn","let","mut","if","return","pub","struct"],
  },
  {
    id: "julia",
    title: "Julia",
    group: "dynamic",
    status: "green",
    suite: "CORE 20-case",
    module: "src/panini/frontends/julia.pni",
    highlight: "Julia function/end",
    errors: "juliaToC leftover",
    sample: "function main()\n    return 0\nend\n",
    blurb: "Frozen frontend. CORE GREEN only.",
    gap: "Julia test suite",
    keywords: ["function","end","return","if","else","for"],
  },
  {
    id: "lua",
    title: "Lua",
    group: "lowhanging",
    status: "green",
    suite: "Lua 5.4 named extract (assert/print/function)",
    module: "src/panini/frontends/lua.pni",
    highlight: "Lua function/end, -- comments",
    errors: "assertion failed / lua expr",
    sample: "function add(a, b)\n  return a + b\nend\nassert(1 + 1 == 2)\nprint(add(40, 2))\n",
    blurb:
      "Low-hanging fruit. Official lua.org 5.4.7 tests are in the tree. This alpha runs a named extract: assert, print, local, function. Full suite remains GAP.",
    gap: "lua-5.4.7 tests skip=0",
    keywords: ["function","end","local","return","if","then","assert","print"],
  },
  {
    id: "zig",
    title: "Zig",
    group: "systems",
    status: "green",
    suite: "CORE 20-case",
    module: "src/panini/frontends/zig.pni",
    highlight: "Zig pub fn",
    errors: "zigToC leftover",
    sample: "pub fn main() i32 { return 0; }\n",
    blurb: "CORE GREEN. zig test suite not retrieved.",
    gap: "zig behavior tests",
    keywords: ["pub","fn","return","const","var","if"],
  },
  {
    id: "make",
    title: "Make",
    group: "kernel",
    status: "green",
    suite: "GNU make manual Setting Variables / echo / deps",
    module: "src/panini/frontends/make.pni",
    highlight: "Make variables, tab recipes, ifeq",
    errors: "print mismatch vs echo",
    sample: "FOO = bar\nall: a\n\techo $(FOO)\na:\n\techo a\n",
    blurb:
      "POSIX/GNU make tokens the kernel build uses: VAR=, ?=, +=, target: deps, tab recipes, $(VAR), $@, $<, $^, ifeq/ifdef, include, obj-y. Not GNU make itself. Not full kbuild.",
    gap: "full GNU make testsuite / kbuild",
    keywords: ["ifeq","ifdef","include","obj-y","PHONY","export"],
  },
  {
    id: "asm",
    title: "GNU as",
    group: "kernel",
    status: "green",
    suite: "gas integer mov/add/ret + comment.s class",
    module: "src/panini/frontends/asm.pni",
    highlight: "AT&T %reg, $imm, .globl",
    errors: "eax/value mismatch",
    sample: ".text\n.globl main\nmain:\n    movl $42, %eax\n    ret\n",
    blurb:
      "AT&T integer subset for kernel .s files. movl/addl/xorl/cmpl/jcc/push/pop/call/ret, directives .globl .text .type .size. Tokens first. Not ld, not ELF.",
    gap: "ld / ELF / full gas testsuite",
    keywords: [".globl",".text","movl","addl","ret","%eax","$imm"],
  },
  {
    id: "kconfig",
    title: "Kconfig",
    group: "kernel",
    status: "green",
    suite: "Linux Kconfig language named extract (config/bool/default)",
    module: "runtime extras (browser)",
    highlight: "config / bool / default / depends",
    errors: "unknown stanza ignored",
    sample: "config PANINI\n\tbool \"Panini kernel token\"\n\tdefault y\n\tdepends on EXPERT\n",
    blurb:
      "Kconfig is how the kernel is configured. Tokens: config, menuconfig, bool, tristate, string, int, hex, default, depends on, select, help, menu, source. Eval applies default y/n.",
    gap: "scripts/kconfig (conf, mconf, nconf)",
    keywords: ["config","bool","tristate","default","depends","select","help"],
  },
  {
    id: "ld",
    title: "GNU ld (script)",
    group: "kernel",
    status: "green",
    suite: "GNU ld script tokens (ENTRY / SECTIONS)",
    module: "runtime extras (browser)",
    highlight: "SECTIONS, ENTRY, KEEP, ALIGN",
    errors: "unrecognised directive listed in tokens only",
    sample: "ENTRY(main)\nSECTIONS {\n  .text : { *(.text) }\n  .data : { *(.data) }\n  .bss  : { *(.bss) }\n}\n",
    blurb:
      "Linker scripts the kernel uses (vmlinux.lds.S class). Tokens: ENTRY, SECTIONS, MEMORY, KEEP, ALIGN, PROVIDE, OUTPUT_FORMAT. Not a linker — tokens + structure, which is what the architect asked for.",
    gap: "actual relocation / ELF emission",
    keywords: ["ENTRY","SECTIONS","KEEP","ALIGN","PROVIDE","MEMORY"],
  },
  {
    id: "scheme",
    title: "Scheme",
    group: "lowhanging",
    status: "green",
    suite: "R5RS integer/define/lambda named extract",
    module: "src/panini/frontends/application.pni (cousin of lisp.pni)",
    highlight: "S-expressions",
    errors: "unknown form",
    sample: "(define (add a b) (+ a b))\n(add 40 2)\n",
    blurb: "Low-hanging fruit: Lisp cousin. define, lambda, if, arithmetic. R5RS/R7RS full suite GAP.",
    gap: "R5RS/R7RS suite skip=0",
    keywords: ["define","lambda","if","quote","let"],
  },
  {
    id: "forth",
    title: "Forth",
    group: "lowhanging",
    status: "green",
    suite: "ANS Forth integer named extract",
    module: "src/panini/frontends/application.pni",
    highlight: "stack words, : ;",
    errors: "unknown word",
    sample: ": ADD + ;\n40 2 ADD .\n",
    blurb: "Low-hanging fruit. Stack machine: +, DUP, SWAP, DROP, ., colon definitions. gforth tests GAP.",
    gap: "gforth tests skip=0",
    keywords: [":",";","DUP","SWAP","DROP","OVER","."],
  },
  {
    id: "ocaml",
    title: "OCaml",
    group: "lowhanging",
    status: "green",
    suite: "OCaml integer let/print_int named extract",
    module: "src/panini/frontends/application.pni",
    highlight: "let / rec / print_int",
    errors: "unlowered pattern match",
    sample: "let add a b = a + b\nlet () = print_int (add 40 2)\n",
    blurb: "Low-hanging fruit. let-bindings and integer expressions. ocaml testsuite GAP.",
    gap: "ocaml testsuite skip=0",
    keywords: ["let","rec","in","if","then","else","match"],
  },
  {
    id: "clojure",
    title: "Clojure",
    group: "lowhanging",
    status: "green",
    suite: "Clojure-shaped list eval (Scheme cousin)",
    module: "src/panini/frontends/application.pni",
    highlight: "S-expressions",
    errors: "unknown form",
    sample: "(defn add [a b] (+ a b))\n(add 40 2)\n",
    blurb: "Lisp cousin. Official Clojure test suite is not skip=0; CORE on the Scheme evaluator.",
    gap: "official Clojure suite",
    keywords: ["defn","def","if","let","fn"],
  },
  {
    id: "csharp",
    title: "C#",
    group: "systems",
    status: "green",
    suite: "ECMA-334 integer Main/Console named extract",
    module: "src/panini/frontends/csharp.pni",
    highlight: "class / Main / Console.WriteLine",
    errors: "unlowered C# leftover",
    sample: "using System;\nclass Program {\n  static int Main() {\n    int n = 40 + 2;\n    Console.WriteLine(n);\n    return n;\n  }\n}\n",
    blurb: "Shaili स्वर. Host-speed desugar to C. Not roslyn.",
    gap: "roslyn / ECMA-334 suite skip=0",
    keywords: ["class","static","int","return","Console","WriteLine","Main"],
  },
  {
    id: "kotlin",
    title: "Kotlin",
    group: "systems",
    status: "green",
    suite: "Kotlin NumbersTest.kt Int.MIN/MAX + one (4)",
    module: "src/panini/frontends/kotlin.pni",
    highlight: "fun / val / println",
    errors: "unlowered Kotlin leftover",
    sample: "fun add(a: Int, b: Int): Int {\n  return a + b\n}\nfun main(): Int {\n  val n = add(40, 2)\n  println(n)\n  return n\n}\n",
    blurb: "Shaili प्रवाह. STANDARD GREEN on NumbersTest.kt Int min/max. Not kotlinc.",
    gap: "Long/Short/Byte overflow / kotlinc box",
    keywords: ["fun","val","var","println","return"],
  },
  {
    id: "swift",
    title: "Swift",
    group: "systems",
    status: "green",
    suite: "Swift IntegerDiagnostics expected-error + simple.swift run (2)",
    module: "src/panini/frontends/swift.pni",
    highlight: "func / let / print",
    errors: "unlowered Swift leftover",
    sample: "func add(a: Int, b: Int) -> Int {\n  return a + b\n}\nfunc main() -> Int {\n  let n = add(40, 2)\n  print(n)\n  return n\n}\n",
    blurb: "Shaili शीघ्र. Apache-2.0 language. Not Apple Swift™. STANDARD GREEN on diagnostics reject + simple.swift.",
    gap: "Full stdlib/Int.swift",
    keywords: ["func","let","var","print","return"],
  },
  {
    id: "scala",
    title: "Scala",
    group: "lowhanging",
    status: "green",
    suite: "Scala t0005.scala def main compile-accept",
    module: "src/panini/frontends/scala.pni",
    highlight: "def / val / object",
    errors: "unlowered Scala leftover",
    sample: "object P {\n  def add(a: Int, b: Int): Int = a + b\n  def main(args: Array[String]): Int = {\n    val n = add(40, 2)\n    println(n)\n    return n\n  }\n}\n",
    blurb: "Shaili सोपान. STANDARD GREEN on t0005.scala compile-accept. Not scalac.",
    gap: "unapply/match execute / full scalac",
    keywords: ["def","val","object","class","println"],
  },
  {
    id: "dart",
    title: "Dart",
    group: "systems",
    status: "green",
    suite: "Dart operator_test.dart i1/i2 Expect.equals integer extract",
    module: "src/panini/frontends/dart.pni",
    highlight: "int / var / print",
    errors: "unlowered Dart leftover",
    sample: "int add(int a, int b) {\n  return a + b;\n}\nint main() {\n  var n = add(40, 2);\n  print(n);\n  return n;\n}\n",
    blurb: "Shaili बाण. STANDARD GREEN on operator_test.dart i1/i2 integer extract.",
    gap: "operator-overload class / language/arithmetic",
    keywords: ["int","void","var","print","return"],
  },
  {
    id: "ada",
    title: "Ada",
    group: "classic",
    status: "green",
    suite: "ISO/IEC 8652 ACATS C45411A unary +/− INTEGER (1)",
    module: "src/panini/frontends/ada.pni",
    highlight: "procedure / function / begin / end",
    errors: "unlowered Ada leftover",
    sample: "function Main return Integer is\n  N : Integer := 40 + 2;\nbegin\n  return N;\nend Main;\n",
    blurb: "Shaili सुरक्षा. STANDARD GREEN / ISO GREEN on ACATS C45411A. Not GNAT.",
    gap: "full ACATS / INTEGER'IMAGE",
    keywords: ["procedure","function","is","begin","end","return","Integer"],
  },
  {
    id: "ruby",
    title: "Ruby",
    group: "dynamic",
    status: "green",
    suite: "ISO/IEC 30170-shaped def/puts named extract",
    module: "src/panini/frontends/ruby.pni",
    highlight: "def / end / puts",
    errors: "ruby expr",
    sample: "def add(a, b)\n  a + b\nend\nputs add(40, 2)\n",
    blurb: "Shaili माणिक्य. Integer def/puts. Not MRI.",
    gap: "MRI / RubySpec skip=0",
    keywords: ["def","end","puts","print","if","else"],
  },
  {
    id: "perl",
    title: "Perl",
    group: "dynamic",
    status: "green",
    suite: "Perl integer sub/print named extract",
    module: "src/panini/frontends/perl.pni",
    highlight: "sub / my / print",
    errors: "perl expr",
    sample: "sub add {\n  my ($a, $b) = @_;\n  return $a + $b;\n}\nprint add(40, 2);\n",
    blurb: "Shaili मोती. Integer sub/print. Not perl.",
    gap: "perlpolicy suite skip=0",
    keywords: ["sub","my","print","say","return"],
  },
  {
    id: "php",
    title: "PHP",
    group: "dynamic",
    status: "green",
    suite: "PHP integer function/echo named extract",
    module: "src/panini/frontends/php.pni",
    highlight: "function / echo",
    errors: "php expr",
    sample: "<?php\nfunction add($a, $b) {\n  return $a + $b;\n}\necho add(40, 2);\n",
    blurb: "Shaili जालधर. Integer function/echo.",
    gap: "php-src suite skip=0",
    keywords: ["function","echo","print","return"],
  },
  {
    id: "r",
    title: "R",
    group: "dynamic",
    status: "green",
    suite: "GNU R simple-true.R 1:12 cumsum + typeof integer L (5)",
    module: "src/panini/frontends/r.pni",
    highlight: "function / <- / print",
    errors: "R expr",
    sample: "add <- function(a, b) { a + b }\nprint(add(40, 2))\n",
    blurb: "Shaili गणना. STANDARD GREEN on GNU R simple-true.R integer extract.",
    gap: "lowess/polyroot/float",
    keywords: ["function","if","else","print","TRUE","FALSE"],
  },
  {
    id: "cobol",
    title: "COBOL",
    group: "classic",
    status: "green",
    suite: "ISO/IEC 1989 integer COMPUTE/DISPLAY named extract",
    module: "src/panini/frontends/cobol.pni",
    highlight: "COMPUTE / DISPLAY / PIC",
    errors: "cobol leftover",
    sample: "IDENTIFICATION DIVISION.\nPROGRAM-ID. ADDN.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC 9(4) VALUE 40.\nPROCEDURE DIVISION.\n    COMPUTE N = N + 2\n    DISPLAY N\n    STOP RUN.\n",
    blurb: "Shaili व्यवसाय. Integer COMPUTE/DISPLAY. gnucobol suite GAP.",
    gap: "gnucobol suite skip=0",
    keywords: ["IDENTIFICATION","DIVISION","COMPUTE","DISPLAY","STOP","RUN"],
  },
  {
    id: "sql",
    title: "SQL",
    group: "classic",
    status: "green",
    suite: "ISO/IEC 9075 integer SELECT/INSERT named extract",
    module: "src/panini/frontends/sql.pni",
    highlight: "SELECT / INSERT / CREATE TABLE",
    errors: "sql expr",
    sample: "CREATE TABLE t (n INT);\nINSERT INTO t VALUES (40);\nSELECT n + 2 FROM t;\n",
    blurb: "Shaili सूत्र. Integer SELECT/INSERT. Not a DBMS.",
    gap: "ISO 9075 suite skip=0",
    keywords: ["SELECT","FROM","WHERE","INSERT","INTO","VALUES","CREATE","TABLE"],
  },
  {
    id: "octave",
    title: "GNU Octave",
    group: "dynamic",
    status: "green",
    suite: "GNU Octave M-file integer function/disp named extract",
    module: "src/panini/frontends/octave.pni",
    highlight: "function / disp / end",
    errors: "octave expr",
    sample: "function r = add(a, b)\n  r = a + b;\nend\nfunction r = main()\n  n = add(40, 2);\n  disp(n);\n  r = n;\nend\n",
    blurb: "Shaili मातृका. GNU Octave M files. Not MATLAB.",
    gap: "Octave test suite skip=0",
    keywords: ["function","end","endfunction","disp","if","else"],
  },
  {
    id: "sysml",
    title: "SysML",
    group: "classic",
    status: "green",
    suite: "SysML v2 textual package/part/constraint named extract",
    module: "src/panini/frontends/sysml.pni",
    highlight: "package / part / constraint",
    errors: "sysml leftover",
    sample: "package Demo {\n  part def Motor {\n    attribute power : Integer = 40;\n  }\n  constraint def Add { 40 + 2 }\n}\n",
    blurb: "Shaili नक्शा. SysML v2 textual. Not a model checker.",
    gap: "full SysML v2 model-check",
    keywords: ["package","part","def","attribute","constraint","requirement"],
  },
  {
    id: "panini",
    title: "PANINI",
    group: "panini",
    status: "green",
    suite: "Stage-0 integer FUNCTION/IF/RETURN/PRINT",
    module: "src/panini/lexer.pni + parser.pni",
    highlight: "FUNCTION END IF RETURN PRINT",
    errors: "unknown function / expr",
    sample:
      "FUNCTION factorial(n:Int) -> Int\n    IF n <= 1\n        RETURN 1\n    ELSE\n        RETURN n * factorial(n - 1)\n    END\nEND\n\nFUNCTION main() -> Int\n    PRINT factorial(6)\n    RETURN 0\nEND\n",
    blurb:
      "The language itself. Browser runs the integer core. Node self-host is a fixed point on 36 functions. Blocks close with END.",
    gap: "browser is a subset of the Node host parser",
    keywords: ["MODULE","FUNCTION","END","IF","ELSE","WHILE","RETURN","PRINT","CONSTITUTION"],
  },
  {
    id: "logo",
    title: "Logo",
    group: "classic",
    status: "green",
    suite: "UCBLogo named extract (REPEAT / FORWARD / RIGHT)",
    module: "runtime extras (browser)",
    highlight: "REPEAT FORWARD RIGHT",
    errors: "unknown primitive",
    sample: "REPEAT 4 [ FORWARD 50 RIGHT 90 ]\n",
    blurb: "Turtle integer extract. Hindi primitives (आगे, दाएँ) sit on the same runner.",
    gap: "full UCBLogo suite",
    keywords: ["REPEAT","FORWARD","BACK","RIGHT","LEFT","PENUP","PENDOWN"],
  },
  {
    id: "lex",
    title: "Lex / flex",
    group: "kernel",
    status: "green",
    suite: "flex named extract (pattern { printf })",
    module: "runtime extras (browser)",
    highlight: "%% pattern action",
    errors: "no rule",
    sample: "%%\n\"ab+\"  { printf(\"match\"); }\n%%\n",
    blurb: "Tokens first. pattern → printf. POSIX lex / full flex suite is GAP.",
    gap: "POSIX lex / full flex",
    keywords: ["%%","printf"],
  },
  {
    id: "yacc",
    title: "Yacc / bison",
    group: "kernel",
    status: "green",
    suite: "yacc calculator named extract",
    module: "runtime extras (browser)",
    highlight: "expr : $$ $1",
    errors: "no rule",
    sample: "expr: expr '+' expr { $$ = $1 + $3; }\n    | NUMBER\n    ;\n",
    blurb: "Calculator named extract from HindiYACC host. Full POSIX yacc is GAP.",
    gap: "full POSIX yacc",
    keywords: ["expr","NUMBER","%%"],
  },
];

export const FRONTEND_BY_ID: Record<string, Frontend> = Object.fromEntries(
  FRONTENDS.map((f) => [f.id, f]),
);

export function greenCount() {
  return FRONTENDS.filter((f) => f.status === "green").length;
}
export function coreCount() {
  return FRONTENDS.filter((f) => f.status === "core").length;
}
