/* Copyright (C) 1993-2026 Abhishek Choudhary | GPL-3.0-or-later
 * ILM C-keyword tables. Hindi bar = 29. Existing translations kept.
 */
export type KeywordRow = { native: string; romenagri: string; c: string; source?: string; fill?: boolean };
export type IlmLanguage = {
  id: string; title: string; script: string; family: string; roundtrip: string;
  n: number; unique_c: number; bar: number; complete: boolean; filled_c: string[]; rows: KeywordRow[];
};
export const HINDI_BAR = 29;
export const ILM_LANGUAGES: Record<string, IlmLanguage> = {
  "arabic": {
    id: "arabic", title: "Arabic", script: "Arabic", family: "perso", roundtrip: "lossy-abjad",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: [],
    rows: [
      { native: "إذا", romenagri: "izaa", c: "if", source: "tsv" },
      { native: "وإلا", romenagri: "vaillaa", c: "else", source: "tsv" },
      { native: "طالما", romenagri: "taalamaa", c: "while", source: "tsv" },
      { native: "افعل", romenagri: "ifaela", c: "do", source: "tsv" },
      { native: "لكل", romenagri: "likulli", c: "for", source: "tsv" },
      { native: "اكسر", romenagri: "iksira", c: "break", source: "tsv" },
      { native: "استمر", romenagri: "istamirra", c: "continue", source: "tsv" },
      { native: "بدل", romenagri: "baddila", c: "switch", source: "tsv" },
      { native: "حالة", romenagri: "haalah", c: "case", source: "tsv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "default", source: "tsv" },
      { native: "أرجع", romenagri: "arjie", c: "return", source: "tsv" },
      { native: "ثابت", romenagri: "saabita", c: "const", source: "tsv" },
      { native: "صحيح", romenagri: "sahiiha", c: "int", source: "tsv" },
      { native: "عائم", romenagri: "aaima", c: "float", source: "tsv" },
      { native: "مزدوج", romenagri: "muzdavija", c: "double", source: "tsv" },
      { native: "حرف", romenagri: "harfa", c: "char", source: "tsv" },
      { native: "فراغ", romenagri: "faraagha", c: "void", source: "tsv" },
      { native: "دالة", romenagri: "daalah", c: "void", source: "tsv" },
      { native: "صنف", romenagri: "sanfa", c: "class", source: "tsv" },
      { native: "جديد", romenagri: "jadiida", c: "new", source: "tsv" },
      { native: "عام", romenagri: "aamma", c: "public", source: "tsv" },
      { native: "خاص", romenagri: "khaassa", c: "private", source: "tsv" },
      { native: "ساكن", romenagri: "saakina", c: "static", source: "tsv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "virtual", source: "tsv" },
      { native: "عندما", romenagri: "indamaa", c: "case", source: "tsv" },
      { native: "بنية", romenagri: "binyah", c: "struct", source: "tsv" },
      { native: "ضمن", romenagri: "dammina", c: "include", source: "tsv" },
      { native: "اقرأ", romenagri: "iqraa", c: "scanf", source: "tsv" },
      { native: "اكتب", romenagri: "uktuba", c: "printf", source: "tsv" },
    ],
  },
  "aramaic": {
    id: "aramaic", title: "Aramaic", script: "Aramaic", family: "semitic", roundtrip: "inventory",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["else", "while", "for", "break", "continue", "switch", "case", "default", "return", "const", "int", "float", "double", "char", "void", "void", "class", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "𐡄𐡍", romenagri: "hana", c: "if", source: "tsv" },
      { native: "אחרת", romenagri: "aharata", c: "else", fill: true, source: "hebrew-hub" },
      { native: "כלעוד", romenagri: "kalaeauda", c: "while", fill: true, source: "hebrew-hub" },
      { native: "𐡏𐡁𐡃", romenagri: "aebada", c: "do", source: "tsv" },
      { native: "עבור", romenagri: "aebuura", c: "for", fill: true, source: "hebrew-hub" },
      { native: "שבור", romenagri: "shvor", c: "break", fill: true, source: "hebrew-hub" },
      { native: "המשך", romenagri: "hemshech", c: "continue", fill: true, source: "hebrew-hub" },
      { native: "בחר", romenagri: "bchar", c: "switch", fill: true, source: "hebrew-hub" },
      { native: "מקרה", romenagri: "mikre", c: "case", fill: true, source: "hebrew-hub" },
      { native: "ברירתמחדל", romenagri: "briratmachdal", c: "default", fill: true, source: "hebrew-hub" },
      { native: "החזר", romenagri: "hahazara", c: "return", fill: true, source: "hebrew-hub" },
      { native: "קבוע", romenagri: "kavuа", c: "const", fill: true, source: "hebrew-hub" },
      { native: "שלם", romenagri: "shalem", c: "int", fill: true, source: "hebrew-hub" },
      { native: "צף", romenagri: "tsaf", c: "float", fill: true, source: "hebrew-hub" },
      { native: "כפול", romenagri: "kaful", c: "double", fill: true, source: "hebrew-hub" },
      { native: "תו", romenagri: "tav", c: "char", fill: true, source: "hebrew-hub" },
      { native: "פונקציה", romenagri: "puunaqaeiyah", c: "void", fill: true, source: "hebrew-hub" },
      { native: "ריק", romenagri: "rek", c: "void", fill: true, source: "hebrew-hub" },
      { native: "מחלקה", romenagri: "mahalaqah", c: "class", fill: true, source: "hebrew-hub" },
      { native: "חדש", romenagri: "chadash", c: "new", fill: true, source: "hebrew-hub" },
      { native: "ציבורי", romenagri: "tsiburi", c: "public", fill: true, source: "hebrew-hub" },
      { native: "פרטי", romenagri: "prati", c: "private", fill: true, source: "hebrew-hub" },
      { native: "סטטי", romenagri: "stati", c: "static", fill: true, source: "hebrew-hub" },
      { native: "מדומה", romenagri: "medume", c: "virtual", fill: true, source: "hebrew-hub" },
      { native: "כאשר", romenagri: "kaasher", c: "case", fill: true, source: "hebrew-hub" },
      { native: "מבנה", romenagri: "mivne", c: "struct", fill: true, source: "hebrew-hub" },
      { native: "כלול", romenagri: "kalul", c: "include", fill: true, source: "hebrew-hub" },
      { native: "קרא", romenagri: "kra", c: "scanf", fill: true, source: "hebrew-hub" },
      { native: "כתוב", romenagri: "ktov", c: "printf", fill: true, source: "hebrew-hub" },
    ],
  },
  "assamese": {
    id: "assamese", title: "Assamese", script: "Bengali-Assamese", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["break", "continue", "switch", "case", "default", "const", "int", "float", "double", "char", "void", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "যদি", romenagri: "yadi", c: "if", source: "tsv" },
      { native: "অন্যথা", romenagri: "anyathaa", c: "else", source: "tsv" },
      { native: "যেতিয়ালৈ", romenagri: "yeetiyaalai", c: "while", source: "tsv" },
      { native: "কৰা", romenagri: "karaa", c: "do", source: "tsv" },
      { native: "বাবে", romenagri: "baabee", c: "for", source: "tsv" },
      { native: "বিৰতি", romenagri: "birati", c: "break", fill: true, source: "fill-literary" },
      { native: "অব্যাহত", romenagri: "abyaahata", c: "continue", fill: true, source: "fill-literary" },
      { native: "নিৰ্বাচন", romenagri: "nirbaacana", c: "switch", fill: true, source: "fill-literary" },
      { native: "অৱস্থা", romenagri: "avasthaa", c: "case", fill: true, source: "fill-literary" },
      { native: "মূল", romenagri: "muula", c: "default", fill: true, source: "fill-literary" },
      { native: "ঘূৰাই", romenagri: "ghuuraai", c: "return", source: "tsv" },
      { native: "ধ্ৰুৱক", romenagri: "dhrubaka", c: "const", fill: true, source: "fill-literary" },
      { native: "পূৰ্ণসংখ্যা", romenagri: "puurnasa_nkhyaa", c: "int", fill: true, source: "fill-literary" },
      { native: "দশমিক", romenagri: "dashamika", c: "float", fill: true, source: "fill-literary" },
      { native: "দ্বিগুণ", romenagri: "dvigu_na", c: "double", fill: true, source: "fill-literary" },
      { native: "আখৰ", romenagri: "aakhara", c: "char", fill: true, source: "fill-literary" },
      { native: "কাৰ্য", romenagri: "kaarya", c: "void", source: "tsv" },
      { native: "শূন্য", romenagri: "shuunya", c: "void", fill: true, source: "fill-literary" },
      { native: "শ্ৰেণী", romenagri: "shree_nii", c: "class", source: "tsv" },
      { native: "নতুন", romenagri: "natuna", c: "new", fill: true, source: "fill-literary" },
      { native: "ৰাজহুৱা", romenagri: "raajahuwaa", c: "public", fill: true, source: "fill-literary" },
      { native: "ব্যক্তিগত", romenagri: "byaktigata", c: "private", fill: true, source: "fill-literary" },
      { native: "স্থিৰ", romenagri: "sthira", c: "static", fill: true, source: "fill-literary" },
      { native: "আভাসী", romenagri: "aabhaasii", c: "virtual", fill: true, source: "fill-literary" },
      { native: "যেতিয়া", romenagri: "yeetiyaa", c: "case", fill: true, source: "fill-literary" },
      { native: "গঠন", romenagri: "gathana", c: "struct", fill: true, source: "fill-literary" },
      { native: "অন্তৰ্ভুক্ত", romenagri: "antarbhukta", c: "include", fill: true, source: "fill-literary" },
      { native: "পঢ়ক", romenagri: "pa_dhaka", c: "scanf", fill: true, source: "fill-literary" },
      { native: "লিখক", romenagri: "likhaka", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "bengali": {
    id: "bengali", title: "Bengali", script: "Bengali", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["include", "scanf", "printf"],
    rows: [
      { native: "যদি", romenagri: "yadi", c: "if", source: "tsv" },
      { native: "অন্যথা", romenagri: "anyathaa", c: "else", source: "tsv" },
      { native: "যতক্ষণ", romenagri: "yatak_sa_na", c: "while", source: "tsv" },
      { native: "করো", romenagri: "karau", c: "do", source: "tsv" },
      { native: "জন্য", romenagri: "janya", c: "for", source: "tsv" },
      { native: "বিরতি", romenagri: "birati", c: "break", source: "tsv" },
      { native: "চালু", romenagri: "caalu", c: "continue", source: "tsv" },
      { native: "নির্বাচন", romenagri: "nirbaacana", c: "switch", source: "tsv" },
      { native: "ক্ষেত্র", romenagri: "k_seetra", c: "case", source: "tsv" },
      { native: "পূর্বনির্ধারিত", romenagri: "puurbanirdhaarita", c: "default", source: "tsv" },
      { native: "ফেরত", romenagri: "pheerata", c: "return", source: "tsv" },
      { native: "ধ্রুবক", romenagri: "dhrubaka", c: "const", source: "tsv" },
      { native: "পূর্ণসংখ্যা", romenagri: "puur_nasa_nkhyaa", c: "int", source: "tsv" },
      { native: "দশমিক", romenagri: "dashamika", c: "float", source: "tsv" },
      { native: "দ্বিগুণ", romenagri: "dbigu_na", c: "double", source: "tsv" },
      { native: "অক্ষর", romenagri: "ak_sara", c: "char", source: "tsv" },
      { native: "শূন্য", romenagri: "shuunya", c: "void", source: "tsv" },
      { native: "কাজ", romenagri: "kaaja", c: "void", source: "tsv" },
      { native: "শ্রেণী", romenagri: "shree_nii", c: "class", source: "tsv" },
      { native: "নতুন", romenagri: "natuna", c: "new", source: "tsv" },
      { native: "সর্বজনীন", romenagri: "sarbajaniina", c: "public", source: "tsv" },
      { native: "ব্যক্তিগত", romenagri: "byaktigata", c: "private", source: "tsv" },
      { native: "স্থির", romenagri: "sthira", c: "static", source: "tsv" },
      { native: "আভাসী", romenagri: "aabhaasii", c: "virtual", source: "tsv" },
      { native: "যখন", romenagri: "yakhana", c: "case", source: "tsv" },
      { native: "কাঠামো", romenagri: "kaathaamau", c: "struct", source: "tsv" },
      { native: "অন্তর্ভুক্ত", romenagri: "antarbhukta", c: "include", fill: true, source: "fill-literary" },
      { native: "পড়ো", romenagri: "pa_dau", c: "scanf", fill: true, source: "fill-literary" },
      { native: "লেখো", romenagri: "lekhau", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "dari": {
    id: "dari", title: "Dari", script: "Perso-Arabic", family: "perso", roundtrip: "lossy-abjad",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["if", "else", "while", "do", "for", "break", "continue", "switch", "case", "default", "return", "const", "int", "float", "double", "char", "void", "void", "class", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "إذا", romenagri: "izaa", c: "if", fill: true, source: "csv:lang_dari.csv" },
      { native: "وإلا", romenagri: "vaillaa", c: "else", fill: true, source: "csv:lang_dari.csv" },
      { native: "طالما", romenagri: "taalamaa", c: "while", fill: true, source: "csv:lang_dari.csv" },
      { native: "افعل", romenagri: "ifaela", c: "do", fill: true, source: "csv:lang_dari.csv" },
      { native: "لكل", romenagri: "likulli", c: "for", fill: true, source: "csv:lang_dari.csv" },
      { native: "اكسر", romenagri: "iksira", c: "break", fill: true, source: "csv:lang_dari.csv" },
      { native: "استمر", romenagri: "istamirra", c: "continue", fill: true, source: "csv:lang_dari.csv" },
      { native: "بدل", romenagri: "baddila", c: "switch", fill: true, source: "csv:lang_dari.csv" },
      { native: "حالة", romenagri: "haalah", c: "case", fill: true, source: "csv:lang_dari.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "default", fill: true, source: "csv:lang_dari.csv" },
      { native: "أرجع", romenagri: "arjie", c: "return", fill: true, source: "csv:lang_dari.csv" },
      { native: "ثابت", romenagri: "saabita", c: "const", fill: true, source: "csv:lang_dari.csv" },
      { native: "صحيح", romenagri: "sahiiha", c: "int", fill: true, source: "csv:lang_dari.csv" },
      { native: "عائم", romenagri: "aaima", c: "float", fill: true, source: "csv:lang_dari.csv" },
      { native: "مزدوج", romenagri: "muzdavija", c: "double", fill: true, source: "csv:lang_dari.csv" },
      { native: "حرف", romenagri: "harfa", c: "char", fill: true, source: "csv:lang_dari.csv" },
      { native: "فراغ", romenagri: "faraagha", c: "void", fill: true, source: "csv:lang_dari.csv" },
      { native: "دالة", romenagri: "daalah", c: "void", fill: true, source: "csv:lang_dari.csv" },
      { native: "صنف", romenagri: "sanfa", c: "class", fill: true, source: "csv:lang_dari.csv" },
      { native: "جديد", romenagri: "jadiida", c: "new", fill: true, source: "csv:lang_dari.csv" },
      { native: "عام", romenagri: "aamma", c: "public", fill: true, source: "csv:lang_dari.csv" },
      { native: "خاص", romenagri: "khaassa", c: "private", fill: true, source: "csv:lang_dari.csv" },
      { native: "ساكن", romenagri: "saakina", c: "static", fill: true, source: "csv:lang_dari.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "virtual", fill: true, source: "csv:lang_dari.csv" },
      { native: "عندما", romenagri: "indamaa", c: "case", fill: true, source: "csv:lang_dari.csv" },
      { native: "بنية", romenagri: "binyah", c: "struct", fill: true, source: "csv:lang_dari.csv" },
      { native: "ضمن", romenagri: "dammina", c: "include", fill: true, source: "csv:lang_dari.csv" },
      { native: "اقرأ", romenagri: "iqraa", c: "scanf", fill: true, source: "csv:lang_dari.csv" },
      { native: "اكتب", romenagri: "uktuba", c: "printf", fill: true, source: "csv:lang_dari.csv" },
    ],
  },
  "gujarati": {
    id: "gujarati", title: "Gujarati", script: "Gujarati", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["include", "scanf", "printf"],
    rows: [
      { native: "જો", romenagri: "jau", c: "if", source: "tsv" },
      { native: "નહીંતર", romenagri: "nahii_ntara", c: "else", source: "tsv" },
      { native: "જ્યાંસુધી", romenagri: "jyaa_nsudhii", c: "while", source: "tsv" },
      { native: "કરો", romenagri: "karau", c: "do", source: "tsv" },
      { native: "માટે", romenagri: "maatee", c: "for", source: "tsv" },
      { native: "તોડો", romenagri: "taudau", c: "break", source: "tsv" },
      { native: "ચાલુ", romenagri: "caalu", c: "continue", source: "tsv" },
      { native: "પસંદગી", romenagri: "pasa_ndagii", c: "switch", source: "tsv" },
      { native: "સ્થિતિ", romenagri: "sthiti", c: "case", source: "tsv" },
      { native: "મૂળભૂત", romenagri: "muulabhuuta", c: "default", source: "tsv" },
      { native: "પાછા", romenagri: "paachaa", c: "return", source: "tsv" },
      { native: "અચલ", romenagri: "acala", c: "const", source: "tsv" },
      { native: "પૂર્ણાંક", romenagri: "puur_naa_nka", c: "int", source: "tsv" },
      { native: "દશાંશ", romenagri: "dashaa_nsha", c: "float", source: "tsv" },
      { native: "દ્વિગુણ", romenagri: "dvigu_na", c: "double", source: "tsv" },
      { native: "અક્ષર", romenagri: "ak_sara", c: "char", source: "tsv" },
      { native: "શૂન્ય", romenagri: "shuunya", c: "void", source: "tsv" },
      { native: "વિધેય", romenagri: "vidheeya", c: "void", source: "tsv" },
      { native: "વર્ગ", romenagri: "varga", c: "class", source: "tsv" },
      { native: "નવું", romenagri: "navu_n", c: "new", source: "tsv" },
      { native: "જાહેર", romenagri: "jaaheera", c: "public", source: "tsv" },
      { native: "ખાનગી", romenagri: "khaanagii", c: "private", source: "tsv" },
      { native: "સ્થિર", romenagri: "sthira", c: "static", source: "tsv" },
      { native: "આભાસી", romenagri: "aabhaasii", c: "virtual", source: "tsv" },
      { native: "જ્યારે", romenagri: "jyaaree", c: "case", source: "tsv" },
      { native: "સંરચના", romenagri: "sa_nracanaa", c: "struct", source: "tsv" },
      { native: "સમાવેશ", romenagri: "samaavesha", c: "include", fill: true, source: "fill-literary" },
      { native: "વાંચો", romenagri: "vaa_nco", c: "scanf", fill: true, source: "fill-literary" },
      { native: "લખો", romenagri: "lakho", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "hebrew": {
    id: "hebrew", title: "Hebrew", script: "Hebrew", family: "semitic", roundtrip: "lossy-abjad",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["break", "continue", "switch", "case", "default", "const", "int", "float", "double", "char", "void", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "אם", romenagri: "ama", c: "if", source: "tsv" },
      { native: "אחרת", romenagri: "aharata", c: "else", source: "tsv" },
      { native: "כלעוד", romenagri: "kalaeauda", c: "while", source: "tsv" },
      { native: "עשה", romenagri: "aeshah", c: "do", source: "tsv" },
      { native: "עבור", romenagri: "aebuura", c: "for", source: "tsv" },
      { native: "שבור", romenagri: "shvor", c: "break", fill: true, source: "fill-literary" },
      { native: "המשך", romenagri: "hemshech", c: "continue", fill: true, source: "fill-literary" },
      { native: "בחר", romenagri: "bchar", c: "switch", fill: true, source: "fill-literary" },
      { native: "מקרה", romenagri: "mikre", c: "case", fill: true, source: "fill-literary" },
      { native: "ברירתמחדל", romenagri: "briratmachdal", c: "default", fill: true, source: "fill-literary" },
      { native: "החזר", romenagri: "hahazara", c: "return", source: "tsv" },
      { native: "קבוע", romenagri: "kavuа", c: "const", fill: true, source: "fill-literary" },
      { native: "שלם", romenagri: "shalem", c: "int", fill: true, source: "fill-literary" },
      { native: "צף", romenagri: "tsaf", c: "float", fill: true, source: "fill-literary" },
      { native: "כפול", romenagri: "kaful", c: "double", fill: true, source: "fill-literary" },
      { native: "תו", romenagri: "tav", c: "char", fill: true, source: "fill-literary" },
      { native: "פונקציה", romenagri: "puunaqaeiyah", c: "void", source: "tsv" },
      { native: "ריק", romenagri: "rek", c: "void", fill: true, source: "fill-literary" },
      { native: "מחלקה", romenagri: "mahalaqah", c: "class", source: "tsv" },
      { native: "חדש", romenagri: "chadash", c: "new", fill: true, source: "fill-literary" },
      { native: "ציבורי", romenagri: "tsiburi", c: "public", fill: true, source: "fill-literary" },
      { native: "פרטי", romenagri: "prati", c: "private", fill: true, source: "fill-literary" },
      { native: "סטטי", romenagri: "stati", c: "static", fill: true, source: "fill-literary" },
      { native: "מדומה", romenagri: "medume", c: "virtual", fill: true, source: "fill-literary" },
      { native: "כאשר", romenagri: "kaasher", c: "case", fill: true, source: "fill-literary" },
      { native: "מבנה", romenagri: "mivne", c: "struct", fill: true, source: "fill-literary" },
      { native: "כלול", romenagri: "kalul", c: "include", fill: true, source: "fill-literary" },
      { native: "קרא", romenagri: "kra", c: "scanf", fill: true, source: "fill-literary" },
      { native: "כתוב", romenagri: "ktov", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "hindi": {
    id: "hindi", title: "Hindi", script: "Devanagari", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: [],
    rows: [
      { native: "यदि", romenagri: "yadi", c: "if", source: "tsv" },
      { native: "अन्यथा", romenagri: "anyathaa", c: "else", source: "tsv" },
      { native: "जबतक", romenagri: "jabataka", c: "while", source: "tsv" },
      { native: "करो", romenagri: "karau", c: "do", source: "tsv" },
      { native: "हेतु", romenagri: "heetu", c: "for", source: "tsv" },
      { native: "विराम", romenagri: "viraama", c: "break", source: "tsv" },
      { native: "जारी", romenagri: "jaarii", c: "continue", source: "tsv" },
      { native: "चयन", romenagri: "cayana", c: "switch", source: "tsv" },
      { native: "स्थिति", romenagri: "sthiti", c: "case", source: "tsv" },
      { native: "मूल", romenagri: "muula", c: "default", source: "tsv" },
      { native: "लौटाओ", romenagri: "lautaaau", c: "return", source: "tsv" },
      { native: "अचर", romenagri: "acara", c: "const", source: "tsv" },
      { native: "पूर्णांक", romenagri: "puur_naa_nka", c: "int", source: "tsv" },
      { native: "दशमलव", romenagri: "dashamalava", c: "float", source: "tsv" },
      { native: "द्विगुण", romenagri: "dviguu_na", c: "double", source: "tsv" },
      { native: "अक्षर", romenagri: "ak_sara", c: "char", source: "tsv" },
      { native: "शून्य", romenagri: "shuunya", c: "void", source: "tsv" },
      { native: "कृत्य", romenagri: "kr_tya", c: "void", source: "tsv" },
      { native: "वर्ग", romenagri: "varga", c: "class", source: "tsv" },
      { native: "नवीन", romenagri: "naviina", c: "new", source: "tsv" },
      { native: "सार्वजनिक", romenagri: "saarvajanika", c: "public", source: "tsv" },
      { native: "निजी", romenagri: "nijii", c: "private", source: "tsv" },
      { native: "स्थिर", romenagri: "sthira", c: "static", source: "tsv" },
      { native: "आभासी", romenagri: "aabhaasii", c: "virtual", source: "tsv" },
      { native: "जब", romenagri: "jaba", c: "case", source: "tsv" },
      { native: "संरचना", romenagri: "sa_nracanaa", c: "struct", source: "tsv" },
      { native: "सम्मिलित", romenagri: "sammilita", c: "include", source: "tsv" },
      { native: "पढ़ो", romenagri: "pa_dau", c: "scanf", source: "tsv" },
      { native: "लिखो", romenagri: "likhau", c: "printf", source: "tsv" },
    ],
  },
  "kannada": {
    id: "kannada", title: "Kannada", script: "Kannada", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["include", "scanf", "printf"],
    rows: [
      { native: "ಆದರೆ", romenagri: "aadaree", c: "if", source: "tsv" },
      { native: "ಇಲ್ಲದಿದ್ದರೆ", romenagri: "illadiddaree", c: "else", source: "tsv" },
      { native: "ತನಕ", romenagri: "tanaka", c: "while", source: "tsv" },
      { native: "ಮಾಡು", romenagri: "maadu", c: "do", source: "tsv" },
      { native: "ಗಾಗಿ", romenagri: "gaagi", c: "for", source: "tsv" },
      { native: "ನಿಲ್ಲಿಸು", romenagri: "nillisu", c: "break", source: "tsv" },
      { native: "ಮುಂದುವರಿ", romenagri: "mu_nduvari", c: "continue", source: "tsv" },
      { native: "ಆಯ್ಕೆ", romenagri: "aayke", c: "switch", source: "tsv" },
      { native: "ಸ್ಥಿತಿ", romenagri: "sthiti", c: "case", source: "tsv" },
      { native: "ಪೂರ್ವನಿಯೋಜಿತ", romenagri: "puurvaniyaujita", c: "default", source: "tsv" },
      { native: "ಹಿಂತಿರುಗಿಸು", romenagri: "hi_ntirugisu", c: "return", source: "tsv" },
      { native: "ಸ್ಥಿರಾಂಕ", romenagri: "sthiraa_nka", c: "const", source: "tsv" },
      { native: "ಪೂರ್ಣಾಂಕ", romenagri: "puur_naa_nka", c: "int", source: "tsv" },
      { native: "ದಶಮಾಂಶ", romenagri: "dashamaa_nsha", c: "float", source: "tsv" },
      { native: "ದ್ವಿಗುಣ", romenagri: "dvigu_na", c: "double", source: "tsv" },
      { native: "ಅಕ್ಷರ", romenagri: "ak_sara", c: "char", source: "tsv" },
      { native: "ಶೂನ್ಯ", romenagri: "shuunya", c: "void", source: "tsv" },
      { native: "ಕಾರ್ಯ", romenagri: "kaarya", c: "void", source: "tsv" },
      { native: "ವರ್ಗ", romenagri: "varga", c: "class", source: "tsv" },
      { native: "ಹೊಸ", romenagri: "hosa", c: "new", source: "tsv" },
      { native: "ಸಾರ್ವಜನಿಕ", romenagri: "saarvajanika", c: "public", source: "tsv" },
      { native: "ಖಾಸಗಿ", romenagri: "khaasagi", c: "private", source: "tsv" },
      { native: "ಸ್ಥಿರ", romenagri: "sthira", c: "static", source: "tsv" },
      { native: "ವಾಸ್ತವಿಕ", romenagri: "vaastavika", c: "virtual", source: "tsv" },
      { native: "ಯಾವಾಗ", romenagri: "yaavaaga", c: "case", source: "tsv" },
      { native: "ರಚನೆ", romenagri: "racane", c: "struct", source: "tsv" },
      { native: "ಸೇರಿಸು", romenagri: "seerisu", c: "include", fill: true, source: "fill-literary" },
      { native: "ಓದು", romenagri: "oodu", c: "scanf", fill: true, source: "fill-literary" },
      { native: "ಬರೆ", romenagri: "bare", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "kashmiri": {
    id: "kashmiri", title: "Kashmiri", script: "Perso-Arabic", family: "perso", roundtrip: "lossy-abjad",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["if", "else", "while", "do", "for", "break", "continue", "switch", "case", "default", "return", "const", "int", "float", "double", "char", "void", "void", "class", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "إذا", romenagri: "izaa", c: "if", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "وإلا", romenagri: "vaillaa", c: "else", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "طالما", romenagri: "taalamaa", c: "while", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "افعل", romenagri: "ifaela", c: "do", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "لكل", romenagri: "likulli", c: "for", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "اكسر", romenagri: "iksira", c: "break", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "استمر", romenagri: "istamirra", c: "continue", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "بدل", romenagri: "baddila", c: "switch", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "حالة", romenagri: "haalah", c: "case", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "default", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "أرجع", romenagri: "arjie", c: "return", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "ثابت", romenagri: "saabita", c: "const", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "صحيح", romenagri: "sahiiha", c: "int", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "عائم", romenagri: "aaima", c: "float", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "مزدوج", romenagri: "muzdavija", c: "double", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "حرف", romenagri: "harfa", c: "char", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "فراغ", romenagri: "faraagha", c: "void", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "دالة", romenagri: "daalah", c: "void", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "صنف", romenagri: "sanfa", c: "class", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "جديد", romenagri: "jadiida", c: "new", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "عام", romenagri: "aamma", c: "public", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "خاص", romenagri: "khaassa", c: "private", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "ساكن", romenagri: "saakina", c: "static", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "virtual", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "عندما", romenagri: "indamaa", c: "case", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "بنية", romenagri: "binyah", c: "struct", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "ضمن", romenagri: "dammina", c: "include", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "اقرأ", romenagri: "iqraa", c: "scanf", fill: true, source: "csv:lang_kashmiri.csv" },
      { native: "اكتب", romenagri: "uktuba", c: "printf", fill: true, source: "csv:lang_kashmiri.csv" },
    ],
  },
  "malayalam": {
    id: "malayalam", title: "Malayalam", script: "Malayalam", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["include", "scanf", "printf"],
    rows: [
      { native: "എങ്കിൽ", romenagri: "e_nkila", c: "if", source: "tsv" },
      { native: "അല്ലെങ്കിൽ", romenagri: "alle_nkila", c: "else", source: "tsv" },
      { native: "വരെ", romenagri: "vare", c: "while", source: "tsv" },
      { native: "ചെയ്യുക", romenagri: "ceyyuka", c: "do", source: "tsv" },
      { native: "വേണ്ടി", romenagri: "ve_ndi", c: "for", source: "tsv" },
      { native: "നിർത്തുക", romenagri: "nirttuka", c: "break", source: "tsv" },
      { native: "തുടരുക", romenagri: "tudaruka", c: "continue", source: "tsv" },
      { native: "തിരഞ്ഞെടുപ്പ്", romenagri: "tira_nyedupp", c: "switch", source: "tsv" },
      { native: "അവസ്ഥ", romenagri: "avastha", c: "case", source: "tsv" },
      { native: "സ്ഥിരസ്ഥിതി", romenagri: "sthirasthiti", c: "default", source: "tsv" },
      { native: "മടക്കുക", romenagri: "madakkuka", c: "return", source: "tsv" },
      { native: "സ്ഥിരം", romenagri: "sthira_m", c: "const", source: "tsv" },
      { native: "പൂർണ്ണസംഖ്യ", romenagri: "puur_n_nasa_mkhya", c: "int", source: "tsv" },
      { native: "ദശാംശം", romenagri: "dashaa_msha_m", c: "float", source: "tsv" },
      { native: "ഇരട്ട", romenagri: "iratta", c: "double", source: "tsv" },
      { native: "അക്ഷരം", romenagri: "ak_sara_m", c: "char", source: "tsv" },
      { native: "ശൂന്യം", romenagri: "shuunya_m", c: "void", source: "tsv" },
      { native: "ധർമ്മം", romenagri: "dharmma_m", c: "void", source: "tsv" },
      { native: "വർഗ്ഗം", romenagri: "varggsa_m", c: "class", source: "tsv" },
      { native: "പുതിയ", romenagri: "putiya", c: "new", source: "tsv" },
      { native: "പൊതു", romenagri: "potu", c: "public", source: "tsv" },
      { native: "സ്വകാര്യ", romenagri: "svakaarya", c: "private", source: "tsv" },
      { native: "സ്ഥിതം", romenagri: "sthita_m", c: "static", source: "tsv" },
      { native: "മായാ", romenagri: "maayaa", c: "virtual", source: "tsv" },
      { native: "എപ്പോൾ", romenagri: "eppaula", c: "case", source: "tsv" },
      { native: "ഘടന", romenagri: "ghatana", c: "struct", source: "tsv" },
      { native: "ഉൾപ്പെടുത്തുക", romenagri: "u_lppetuttuka", c: "include", fill: true, source: "fill-literary" },
      { native: "വായിക്കുക", romenagri: "vaayikkuka", c: "scanf", fill: true, source: "fill-literary" },
      { native: "എഴുതുക", romenagri: "ezhutuka", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "marathi": {
    id: "marathi", title: "Marathi", script: "Devanagari", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["include", "scanf", "printf"],
    rows: [
      { native: "जर", romenagri: "jara", c: "if", source: "tsv" },
      { native: "अन्यथा", romenagri: "anyathaa", c: "else", source: "tsv" },
      { native: "पर्यंत", romenagri: "parya_nta", c: "while", source: "tsv" },
      { native: "करा", romenagri: "karaa", c: "do", source: "tsv" },
      { native: "साठी", romenagri: "saathii", c: "for", source: "tsv" },
      { native: "थांबा", romenagri: "thaa_mbaa", c: "break", source: "tsv" },
      { native: "सुरूठेवा", romenagri: "suruutheevaa", c: "continue", source: "tsv" },
      { native: "निवड", romenagri: "nivada", c: "switch", source: "tsv" },
      { native: "स्थिती", romenagri: "sthitii", c: "case", source: "tsv" },
      { native: "पूर्वनिर्धारित", romenagri: "puurvanirdhaarita", c: "default", source: "tsv" },
      { native: "परत", romenagri: "parata", c: "return", source: "tsv" },
      { native: "स्थिरांक", romenagri: "sthiraa_nka", c: "const", source: "tsv" },
      { native: "पूर्णांक", romenagri: "puur_naa_nka", c: "int", source: "tsv" },
      { native: "दशांश", romenagri: "dashaa_nsha", c: "float", source: "tsv" },
      { native: "द्विगुण", romenagri: "dvigu_na", c: "double", source: "tsv" },
      { native: "अक्षर", romenagri: "ak_sara", c: "char", source: "tsv" },
      { native: "शून्य", romenagri: "shuunya", c: "void", source: "tsv" },
      { native: "कार्य", romenagri: "kaarya", c: "void", source: "tsv" },
      { native: "वर्ग", romenagri: "varga", c: "class", source: "tsv" },
      { native: "नवीन", romenagri: "naviina", c: "new", source: "tsv" },
      { native: "सार्वजनिक", romenagri: "saarvajanika", c: "public", source: "tsv" },
      { native: "खाजगी", romenagri: "khaajagii", c: "private", source: "tsv" },
      { native: "स्थिर", romenagri: "sthira", c: "static", source: "tsv" },
      { native: "आभासी", romenagri: "aabhaasii", c: "virtual", source: "tsv" },
      { native: "जेव्हा", romenagri: "jeevhaa", c: "case", source: "tsv" },
      { native: "संरचना", romenagri: "sa_nracanaa", c: "struct", source: "tsv" },
      { native: "समावेश", romenagri: "samaavesha", c: "include", fill: true, source: "fill-literary" },
      { native: "वाचा", romenagri: "vaacaa", c: "scanf", fill: true, source: "fill-literary" },
      { native: "लिहा", romenagri: "lihaa", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "nepali": {
    id: "nepali", title: "Nepali", script: "Devanagari", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["switch", "case", "default", "int", "float", "double", "char", "void", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "यदि", romenagri: "yadi", c: "if", source: "tsv" },
      { native: "अन्यथा", romenagri: "anyathaa", c: "else", source: "tsv" },
      { native: "जबसम्म", romenagri: "jabasamma", c: "while", source: "tsv" },
      { native: "गर", romenagri: "gara", c: "do", source: "tsv" },
      { native: "लागि", romenagri: "laagi", c: "for", source: "tsv" },
      { native: "रोक", romenagri: "rauka", c: "break", source: "tsv" },
      { native: "जारी", romenagri: "jaarii", c: "continue", source: "tsv" },
      { native: "चयन", romenagri: "cayana", c: "switch", fill: true, source: "fill-literary" },
      { native: "स्थिति", romenagri: "sthiti", c: "case", fill: true, source: "fill-literary" },
      { native: "मूल", romenagri: "muula", c: "default", fill: true, source: "fill-literary" },
      { native: "फर्काऊ", romenagri: "pharakaauu", c: "return", source: "tsv" },
      { native: "अचर", romenagri: "acara", c: "const", source: "tsv" },
      { native: "पूर्णाङ्क", romenagri: "puur_naa_nka", c: "int", fill: true, source: "fill-literary" },
      { native: "दशमलव", romenagri: "dashamalava", c: "float", fill: true, source: "fill-literary" },
      { native: "द्विगुण", romenagri: "dviguu_na", c: "double", fill: true, source: "fill-literary" },
      { native: "अक्षर", romenagri: "ak_sara", c: "char", fill: true, source: "fill-literary" },
      { native: "कार्य", romenagri: "kaarya", c: "void", source: "tsv" },
      { native: "शून्य", romenagri: "shuunya", c: "void", fill: true, source: "fill-literary" },
      { native: "वर्ग", romenagri: "varga", c: "class", source: "tsv" },
      { native: "नयाँ", romenagri: "nayaa_n", c: "new", fill: true, source: "fill-literary" },
      { native: "सार्वजनिक", romenagri: "saarvajanika", c: "public", fill: true, source: "fill-literary" },
      { native: "निजी", romenagri: "nijii", c: "private", fill: true, source: "fill-literary" },
      { native: "स्थिर", romenagri: "sthira", c: "static", fill: true, source: "fill-literary" },
      { native: "आभासी", romenagri: "aabhaasii", c: "virtual", fill: true, source: "fill-literary" },
      { native: "जब", romenagri: "jaba", c: "case", fill: true, source: "fill-literary" },
      { native: "संरचना", romenagri: "sa_nracanaa", c: "struct", fill: true, source: "fill-literary" },
      { native: "समावेश", romenagri: "samaavesha", c: "include", fill: true, source: "fill-literary" },
      { native: "पढ", romenagri: "pa_dha", c: "scanf", fill: true, source: "fill-literary" },
      { native: "लेख", romenagri: "lekha", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "odia": {
    id: "odia", title: "Odia", script: "Odia", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["include", "scanf", "printf"],
    rows: [
      { native: "ଯଦି", romenagri: "yadi", c: "if", source: "tsv" },
      { native: "ଅନ୍ୟଥା", romenagri: "anyathaa", c: "else", source: "tsv" },
      { native: "ଯେପର୍ଯ୍ୟନ୍ତ", romenagri: "yeeparyyanta", c: "while", source: "tsv" },
      { native: "କର", romenagri: "kara", c: "do", source: "tsv" },
      { native: "ପାଇଁ", romenagri: "paaii_n", c: "for", source: "tsv" },
      { native: "ଭାଙ୍ଗ", romenagri: "bhaa_nga", c: "break", source: "tsv" },
      { native: "ଜାରି", romenagri: "jaari", c: "continue", source: "tsv" },
      { native: "ବାଛ", romenagri: "baacha", c: "switch", source: "tsv" },
      { native: "ସ୍ଥିତି", romenagri: "sthiti", c: "case", source: "tsv" },
      { native: "ପୂର୍ବନିର୍ଦ୍ଧାରିତ", romenagri: "puurbanirddhaarita", c: "default", source: "tsv" },
      { native: "ଫେରାଅ", romenagri: "pheeraaa", c: "return", source: "tsv" },
      { native: "ଅଚଳ", romenagri: "acala", c: "const", source: "tsv" },
      { native: "ପୂର୍ଣ୍ଣସଂଖ୍ୟା", romenagri: "puur_n_nasa_mkhyaa", c: "int", source: "tsv" },
      { native: "ଦଶମିକ", romenagri: "dashamika", c: "float", source: "tsv" },
      { native: "ଦ୍ୱିଗୁଣ", romenagri: "dvigu_na", c: "double", source: "tsv" },
      { native: "ଅକ୍ଷର", romenagri: "ak_sara", c: "char", source: "tsv" },
      { native: "ଶୂନ୍ୟ", romenagri: "shuunya", c: "void", source: "tsv" },
      { native: "କାର୍ଯ୍ୟ", romenagri: "kaaryya", c: "void", source: "tsv" },
      { native: "ଶ୍ରେଣୀ", romenagri: "shree_nii", c: "class", source: "tsv" },
      { native: "ନୂତନ", romenagri: "nuutana", c: "new", source: "tsv" },
      { native: "ସର୍ବସାଧାରଣ", romenagri: "sarbasaadhaara_na", c: "public", source: "tsv" },
      { native: "ବ୍ୟକ୍ତିଗତ", romenagri: "byaktigata", c: "private", source: "tsv" },
      { native: "ସ୍ଥିର", romenagri: "sthira", c: "static", source: "tsv" },
      { native: "ଆଭାସୀ", romenagri: "aabhaasii", c: "virtual", source: "tsv" },
      { native: "ଯେତେବେଳେ", romenagri: "yeeteebeelee", c: "case", source: "tsv" },
      { native: "ସଂରଚନା", romenagri: "sa_nracanaa", c: "struct", source: "tsv" },
      { native: "ସାମିଲ", romenagri: "saamila", c: "include", fill: true, source: "fill-literary" },
      { native: "ପଢନ୍ତୁ", romenagri: "pa_dhantu", c: "scanf", fill: true, source: "fill-literary" },
      { native: "ଲେଖନ୍ତୁ", romenagri: "lekhantu", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "pali": {
    id: "pali", title: "Pali", script: "Devanagari", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["break", "continue", "switch", "case", "default", "const", "int", "float", "double", "char", "void", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "सचे", romenagri: "sacee", c: "if", source: "tsv" },
      { native: "अञ्ञथा", romenagri: "anyanyathaa", c: "else", source: "tsv" },
      { native: "याव", romenagri: "yaava", c: "while", source: "tsv" },
      { native: "करोहि", romenagri: "karauhi", c: "do", source: "tsv" },
      { native: "अत्थाय", romenagri: "atthaaya", c: "for", source: "tsv" },
      { native: "भञ्ज", romenagri: "bha_nja", c: "break", fill: true, source: "fill-literary" },
      { native: "अनुवत्त", romenagri: "anuvatta", c: "continue", fill: true, source: "fill-literary" },
      { native: "विकप्प", romenagri: "vikappa", c: "switch", fill: true, source: "fill-literary" },
      { native: "पक्ख", romenagri: "pakkha", c: "case", fill: true, source: "fill-literary" },
      { native: "सभाव", romenagri: "sabhaava", c: "default", fill: true, source: "fill-literary" },
      { native: "पटिनिवत्त", romenagri: "patinivatta", c: "return", source: "tsv" },
      { native: "ध्रुव", romenagri: "dhruva", c: "const", fill: true, source: "fill-literary" },
      { native: "पूर्णङ्क", romenagri: "puur_na_nka", c: "int", fill: true, source: "fill-literary" },
      { native: "भिन्न", romenagri: "bhinna", c: "float", fill: true, source: "fill-literary" },
      { native: "द्विगुण", romenagri: "dvigu_na", c: "double", fill: true, source: "fill-literary" },
      { native: "वण्ण", romenagri: "va_n_na", c: "char", fill: true, source: "fill-literary" },
      { native: "किच्च", romenagri: "kicca", c: "void", source: "tsv" },
      { native: "सुञ्ञ", romenagri: "su_n_na", c: "void", fill: true, source: "fill-literary" },
      { native: "वग्ग", romenagri: "vaggsa", c: "class", source: "tsv" },
      { native: "नव", romenagri: "nava", c: "new", fill: true, source: "fill-literary" },
      { native: "साधारण", romenagri: "saadhaara_na", c: "public", fill: true, source: "fill-literary" },
      { native: "गुत्त", romenagri: "gutta", c: "private", fill: true, source: "fill-literary" },
      { native: "ठित", romenagri: "thita", c: "static", fill: true, source: "fill-literary" },
      { native: "आभास", romenagri: "aabhaasa", c: "virtual", fill: true, source: "fill-literary" },
      { native: "यदा", romenagri: "yadaa", c: "case", fill: true, source: "fill-literary" },
      { native: "सङ्घट", romenagri: "sa_ngha_ta", c: "struct", fill: true, source: "fill-literary" },
      { native: "अन्तोगध", romenagri: "antogadha", c: "include", fill: true, source: "fill-literary" },
      { native: "पठ", romenagri: "patha", c: "scanf", fill: true, source: "fill-literary" },
      { native: "लिख", romenagri: "likha", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "pashto": {
    id: "pashto", title: "Pashto", script: "Perso-Arabic", family: "perso", roundtrip: "lossy-abjad",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["if", "else", "while", "do", "for", "break", "continue", "switch", "case", "default", "return", "const", "int", "float", "double", "char", "void", "void", "class", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "إذا", romenagri: "izaa", c: "if", fill: true, source: "csv:lang_pashto.csv" },
      { native: "وإلا", romenagri: "vaillaa", c: "else", fill: true, source: "csv:lang_pashto.csv" },
      { native: "طالما", romenagri: "taalamaa", c: "while", fill: true, source: "csv:lang_pashto.csv" },
      { native: "افعل", romenagri: "ifaela", c: "do", fill: true, source: "csv:lang_pashto.csv" },
      { native: "لكل", romenagri: "likulli", c: "for", fill: true, source: "csv:lang_pashto.csv" },
      { native: "اكسر", romenagri: "iksira", c: "break", fill: true, source: "csv:lang_pashto.csv" },
      { native: "استمر", romenagri: "istamirra", c: "continue", fill: true, source: "csv:lang_pashto.csv" },
      { native: "بدل", romenagri: "baddila", c: "switch", fill: true, source: "csv:lang_pashto.csv" },
      { native: "حالة", romenagri: "haalah", c: "case", fill: true, source: "csv:lang_pashto.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "default", fill: true, source: "csv:lang_pashto.csv" },
      { native: "أرجع", romenagri: "arjie", c: "return", fill: true, source: "csv:lang_pashto.csv" },
      { native: "ثابت", romenagri: "saabita", c: "const", fill: true, source: "csv:lang_pashto.csv" },
      { native: "صحيح", romenagri: "sahiiha", c: "int", fill: true, source: "csv:lang_pashto.csv" },
      { native: "عائم", romenagri: "aaima", c: "float", fill: true, source: "csv:lang_pashto.csv" },
      { native: "مزدوج", romenagri: "muzdavija", c: "double", fill: true, source: "csv:lang_pashto.csv" },
      { native: "حرف", romenagri: "harfa", c: "char", fill: true, source: "csv:lang_pashto.csv" },
      { native: "فراغ", romenagri: "faraagha", c: "void", fill: true, source: "csv:lang_pashto.csv" },
      { native: "دالة", romenagri: "daalah", c: "void", fill: true, source: "csv:lang_pashto.csv" },
      { native: "صنف", romenagri: "sanfa", c: "class", fill: true, source: "csv:lang_pashto.csv" },
      { native: "جديد", romenagri: "jadiida", c: "new", fill: true, source: "csv:lang_pashto.csv" },
      { native: "عام", romenagri: "aamma", c: "public", fill: true, source: "csv:lang_pashto.csv" },
      { native: "خاص", romenagri: "khaassa", c: "private", fill: true, source: "csv:lang_pashto.csv" },
      { native: "ساكن", romenagri: "saakina", c: "static", fill: true, source: "csv:lang_pashto.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "virtual", fill: true, source: "csv:lang_pashto.csv" },
      { native: "عندما", romenagri: "indamaa", c: "case", fill: true, source: "csv:lang_pashto.csv" },
      { native: "بنية", romenagri: "binyah", c: "struct", fill: true, source: "csv:lang_pashto.csv" },
      { native: "ضمن", romenagri: "dammina", c: "include", fill: true, source: "csv:lang_pashto.csv" },
      { native: "اقرأ", romenagri: "iqraa", c: "scanf", fill: true, source: "csv:lang_pashto.csv" },
      { native: "اكتب", romenagri: "uktuba", c: "printf", fill: true, source: "csv:lang_pashto.csv" },
    ],
  },
  "persian": {
    id: "persian", title: "Persian", script: "Perso-Arabic", family: "perso", roundtrip: "lossy-abjad",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["scanf", "printf"],
    rows: [
      { native: "اگر", romenagri: "agar", c: "if", source: "tsv" },
      { native: "وگرنه", romenagri: "vagarnah", c: "else", source: "tsv" },
      { native: "تازمانیکه", romenagri: "taazamaaniikah", c: "while", source: "tsv" },
      { native: "انجامبده", romenagri: "anjaamabdah", c: "do", source: "tsv" },
      { native: "برای", romenagri: "baraaya", c: "for", source: "tsv" },
      { native: "بشکن", romenagri: "bishkan", c: "break", source: "tsv" },
      { native: "ادامه", romenagri: "adaamah", c: "continue", source: "tsv" },
      { native: "انتخاب", romenagri: "intikhaaba", c: "switch", source: "tsv" },
      { native: "حالت", romenagri: "haalata", c: "case", source: "tsv" },
      { native: "پیشفرض", romenagri: "piishfarza", c: "default", source: "tsv" },
      { native: "بازگرد", romenagri: "baazgard", c: "return", source: "tsv" },
      { native: "ثابت", romenagri: "saabita", c: "const", source: "tsv" },
      { native: "صحیح", romenagri: "sahiiha", c: "int", source: "tsv" },
      { native: "اعشاری", romenagri: "aeshaarii", c: "float", source: "tsv" },
      { native: "دوگانه", romenagri: "daugaanah", c: "double", source: "tsv" },
      { native: "نویسه", romenagri: "naviisah", c: "char", source: "tsv" },
      { native: "تهی", romenagri: "tahii", c: "void", source: "tsv" },
      { native: "تابع", romenagri: "taabe", c: "void", source: "tsv" },
      { native: "رده", romenagri: "radah", c: "class", source: "tsv" },
      { native: "جدید", romenagri: "jadiida", c: "new", source: "tsv" },
      { native: "عمومی", romenagri: "umuumii", c: "public", source: "tsv" },
      { native: "خصوصی", romenagri: "khusuusii", c: "private", source: "tsv" },
      { native: "ایستا", romenagri: "iistaa", c: "static", source: "tsv" },
      { native: "مجازی", romenagri: "majaazii", c: "virtual", source: "tsv" },
      { native: "هنگامیکه", romenagri: "hanagaamiikah", c: "case", source: "tsv" },
      { native: "ساختار", romenagri: "saakhtaara", c: "struct", source: "tsv" },
      { native: "شامل", romenagri: "shaamila", c: "include", source: "tsv" },
      { native: "بخوان", romenagri: "bikhaan", c: "scanf", fill: true, source: "fill-literary" },
      { native: "بنویس", romenagri: "binaviis", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "phoenician": {
    id: "phoenician", title: "Phoenician", script: "Phoenician", family: "semitic", roundtrip: "inventory",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["else", "while", "for", "break", "continue", "switch", "case", "default", "return", "const", "int", "float", "double", "char", "void", "void", "class", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "𐤀𐤌", romenagri: "ama", c: "if", source: "tsv" },
      { native: "אחרת", romenagri: "aharata", c: "else", fill: true, source: "hebrew-hub" },
      { native: "כלעוד", romenagri: "kalaeauda", c: "while", fill: true, source: "hebrew-hub" },
      { native: "𐤐𐤏𐤋", romenagri: "paaela", c: "do", source: "tsv" },
      { native: "עבור", romenagri: "aebuura", c: "for", fill: true, source: "hebrew-hub" },
      { native: "שבור", romenagri: "shvor", c: "break", fill: true, source: "hebrew-hub" },
      { native: "המשך", romenagri: "hemshech", c: "continue", fill: true, source: "hebrew-hub" },
      { native: "בחר", romenagri: "bchar", c: "switch", fill: true, source: "hebrew-hub" },
      { native: "מקרה", romenagri: "mikre", c: "case", fill: true, source: "hebrew-hub" },
      { native: "ברירתמחדל", romenagri: "briratmachdal", c: "default", fill: true, source: "hebrew-hub" },
      { native: "החזר", romenagri: "hahazara", c: "return", fill: true, source: "hebrew-hub" },
      { native: "קבוע", romenagri: "kavuа", c: "const", fill: true, source: "hebrew-hub" },
      { native: "שלם", romenagri: "shalem", c: "int", fill: true, source: "hebrew-hub" },
      { native: "צף", romenagri: "tsaf", c: "float", fill: true, source: "hebrew-hub" },
      { native: "כפול", romenagri: "kaful", c: "double", fill: true, source: "hebrew-hub" },
      { native: "תו", romenagri: "tav", c: "char", fill: true, source: "hebrew-hub" },
      { native: "פונקציה", romenagri: "puunaqaeiyah", c: "void", fill: true, source: "hebrew-hub" },
      { native: "ריק", romenagri: "rek", c: "void", fill: true, source: "hebrew-hub" },
      { native: "מחלקה", romenagri: "mahalaqah", c: "class", fill: true, source: "hebrew-hub" },
      { native: "חדש", romenagri: "chadash", c: "new", fill: true, source: "hebrew-hub" },
      { native: "ציבורי", romenagri: "tsiburi", c: "public", fill: true, source: "hebrew-hub" },
      { native: "פרטי", romenagri: "prati", c: "private", fill: true, source: "hebrew-hub" },
      { native: "סטטי", romenagri: "stati", c: "static", fill: true, source: "hebrew-hub" },
      { native: "מדומה", romenagri: "medume", c: "virtual", fill: true, source: "hebrew-hub" },
      { native: "כאשר", romenagri: "kaasher", c: "case", fill: true, source: "hebrew-hub" },
      { native: "מבנה", romenagri: "mivne", c: "struct", fill: true, source: "hebrew-hub" },
      { native: "כלול", romenagri: "kalul", c: "include", fill: true, source: "hebrew-hub" },
      { native: "קרא", romenagri: "kra", c: "scanf", fill: true, source: "hebrew-hub" },
      { native: "כתוב", romenagri: "ktov", c: "printf", fill: true, source: "hebrew-hub" },
    ],
  },
  "prakrit": {
    id: "prakrit", title: "Prakrit", script: "Devanagari", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["for", "break", "continue", "switch", "case", "default", "return", "const", "int", "float", "double", "char", "void", "void", "class", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "जइ", romenagri: "jai", c: "if", source: "tsv" },
      { native: "अण्णहा", romenagri: "a_n_nahaa", c: "else", source: "tsv" },
      { native: "जाव", romenagri: "jaava", c: "while", source: "tsv" },
      { native: "करेहि", romenagri: "kareehi", c: "do", source: "tsv" },
      { native: "अत्थे", romenagri: "atthe", c: "for", fill: true, source: "fill-literary" },
      { native: "भंग", romenagri: "bha_nga", c: "break", fill: true, source: "fill-literary" },
      { native: "चालु", romenagri: "caalu", c: "continue", fill: true, source: "fill-literary" },
      { native: "विअप्प", romenagri: "viappa", c: "switch", fill: true, source: "fill-literary" },
      { native: "पक्ख", romenagri: "pakkha", c: "case", fill: true, source: "fill-literary" },
      { native: "मूल", romenagri: "muula", c: "default", fill: true, source: "fill-literary" },
      { native: "निअत्त", romenagri: "niatta", c: "return", fill: true, source: "fill-literary" },
      { native: "धुव", romenagri: "dhuva", c: "const", fill: true, source: "fill-literary" },
      { native: "पुण्णंक", romenagri: "pu_n_na_nka", c: "int", fill: true, source: "fill-literary" },
      { native: "भिण्ण", romenagri: "bhi_n_na", c: "float", fill: true, source: "fill-literary" },
      { native: "दुगुण", romenagri: "dugu_na", c: "double", fill: true, source: "fill-literary" },
      { native: "अक्खर", romenagri: "akkhara", c: "char", fill: true, source: "fill-literary" },
      { native: "सुण्ण", romenagri: "su_n_na", c: "void", fill: true, source: "fill-literary" },
      { native: "किरिया", romenagri: "kiriyaa", c: "void", fill: true, source: "fill-literary" },
      { native: "वग्ग", romenagri: "vagga", c: "class", fill: true, source: "fill-literary" },
      { native: "णव", romenagri: "_nava", c: "new", fill: true, source: "fill-literary" },
      { native: "साहत्त", romenagri: "saahatta", c: "public", fill: true, source: "fill-literary" },
      { native: "गुत्त", romenagri: "gutta", c: "private", fill: true, source: "fill-literary" },
      { native: "ठिअ", romenagri: "thia", c: "static", fill: true, source: "fill-literary" },
      { native: "आभास", romenagri: "aabhaasa", c: "virtual", fill: true, source: "fill-literary" },
      { native: "जदा", romenagri: "jadaa", c: "case", fill: true, source: "fill-literary" },
      { native: "संघड", romenagri: "sa_ngha_da", c: "struct", fill: true, source: "fill-literary" },
      { native: "अंतोगध", romenagri: "a_ntogadha", c: "include", fill: true, source: "fill-literary" },
      { native: "पढ", romenagri: "pa_dha", c: "scanf", fill: true, source: "fill-literary" },
      { native: "लिह", romenagri: "liha", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "punjabi": {
    id: "punjabi", title: "Punjabi", script: "Gurmukhi", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["include", "scanf", "printf"],
    rows: [
      { native: "ਜੇ", romenagri: "jee", c: "if", source: "tsv" },
      { native: "ਨਹੀਂਤਾਂ", romenagri: "nahii_ntaa_n", c: "else", source: "tsv" },
      { native: "ਜਦਤੱਕ", romenagri: "jadatakka", c: "while", source: "tsv" },
      { native: "ਕਰੋ", romenagri: "karau", c: "do", source: "tsv" },
      { native: "ਲਈ", romenagri: "laii", c: "for", source: "tsv" },
      { native: "ਰੋਕੋ", romenagri: "raukau", c: "break", source: "tsv" },
      { native: "ਜਾਰੀ", romenagri: "jaarii", c: "continue", source: "tsv" },
      { native: "ਚੋਣ", romenagri: "cau_na", c: "switch", source: "tsv" },
      { native: "ਹਾਲਤ", romenagri: "haalata", c: "case", source: "tsv" },
      { native: "ਮੂਲ", romenagri: "muula", c: "default", source: "tsv" },
      { native: "ਵਾਪਸ", romenagri: "vaapasa", c: "return", source: "tsv" },
      { native: "ਅਚਲ", romenagri: "acala", c: "const", source: "tsv" },
      { native: "ਪੂਰਨਅੰਕ", romenagri: "puurana_nka", c: "int", source: "tsv" },
      { native: "ਦਸ਼ਮਲਵ", romenagri: "dashamalava", c: "float", source: "tsv" },
      { native: "ਦੁੱਗਣਾ", romenagri: "duggsa_naa", c: "double", source: "tsv" },
      { native: "ਅੱਖਰ", romenagri: "akkhara", c: "char", source: "tsv" },
      { native: "ਖਾਲੀ", romenagri: "khaalii", c: "void", source: "tsv" },
      { native: "ਕਾਰਜ", romenagri: "kaaraja", c: "void", source: "tsv" },
      { native: "ਵਰਗ", romenagri: "varga", c: "class", source: "tsv" },
      { native: "ਨਵਾਂ", romenagri: "navaa_n", c: "new", source: "tsv" },
      { native: "ਜਨਤਕ", romenagri: "janataka", c: "public", source: "tsv" },
      { native: "ਨਿਜੀ", romenagri: "nijii", c: "private", source: "tsv" },
      { native: "ਸਥਿਰ", romenagri: "sathira", c: "static", source: "tsv" },
      { native: "ਆਭਾਸੀ", romenagri: "aabhaasii", c: "virtual", source: "tsv" },
      { native: "ਜਦੋਂ", romenagri: "jadau_n", c: "case", source: "tsv" },
      { native: "ਬਣਤਰ", romenagri: "ba_natara", c: "struct", source: "tsv" },
      { native: "ਸ਼ਾਮਲ", romenagri: "shaamala", c: "include", fill: true, source: "fill-literary" },
      { native: "ਪੜ੍ਹੋ", romenagri: "pa_rhau", c: "scanf", fill: true, source: "fill-literary" },
      { native: "ਲਿਖੋ", romenagri: "likhau", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "sanskrit": {
    id: "sanskrit", title: "Sanskrit", script: "Devanagari", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: [],
    rows: [
      { native: "यदि", romenagri: "yadi", c: "if", source: "tsv" },
      { native: "अन्यथा", romenagri: "anyathaa", c: "else", source: "tsv" },
      { native: "यावत्", romenagri: "yaavat", c: "while", source: "tsv" },
      { native: "कुरु", romenagri: "kuru", c: "do", source: "tsv" },
      { native: "प्रति", romenagri: "prati", c: "for", source: "tsv" },
      { native: "भङ्ग", romenagri: "bha_nga", c: "break", source: "tsv" },
      { native: "अनुवर्त", romenagri: "anuvarta", c: "continue", source: "tsv" },
      { native: "विकल्प", romenagri: "vikalpa", c: "switch", source: "tsv" },
      { native: "पक्ष", romenagri: "pak_sa", c: "case", source: "tsv" },
      { native: "स्वभाव", romenagri: "svabhaava", c: "default", source: "tsv" },
      { native: "प्रत्यागम", romenagri: "pratyaagama", c: "return", source: "tsv" },
      { native: "ध्रुव", romenagri: "dhruva", c: "const", source: "tsv" },
      { native: "पूर्णाङ्क", romenagri: "puur_naa_nka", c: "int", source: "tsv" },
      { native: "भिन्न", romenagri: "bhinna", c: "float", source: "tsv" },
      { native: "द्विगुण", romenagri: "dviguu_na", c: "double", source: "tsv" },
      { native: "वर्ण", romenagri: "var_na", c: "char", source: "tsv" },
      { native: "शून्य", romenagri: "shuunya", c: "void", source: "tsv" },
      { native: "क्रिया", romenagri: "kriyaa", c: "void", source: "tsv" },
      { native: "वर्ग", romenagri: "varga", c: "class", source: "tsv" },
      { native: "नूतन", romenagri: "nuutana", c: "new", source: "tsv" },
      { native: "सार्वजनिक", romenagri: "saarvajanika", c: "public", source: "tsv" },
      { native: "गुप्त", romenagri: "gupta", c: "private", source: "tsv" },
      { native: "स्थिर", romenagri: "sthira", c: "static", source: "tsv" },
      { native: "आभास", romenagri: "aabhaasa", c: "virtual", source: "tsv" },
      { native: "यदा", romenagri: "yadaa", c: "case", source: "tsv" },
      { native: "संरचना", romenagri: "sa_nracanaa", c: "struct", source: "tsv" },
      { native: "अन्तर्भाव", romenagri: "antarbhaava", c: "include", source: "tsv" },
      { native: "पठ", romenagri: "patha", c: "scanf", source: "tsv" },
      { native: "लिख", romenagri: "likha", c: "printf", source: "tsv" },
    ],
  },
  "shahmukhi": {
    id: "shahmukhi", title: "Punjabi Shahmukhi", script: "Perso-Arabic (Shahmukhi)", family: "perso", roundtrip: "lossy-abjad",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["if", "else", "while", "do", "for", "break", "continue", "switch", "case", "default", "return", "const", "int", "float", "double", "char", "void", "void", "class", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "إذا", romenagri: "izaa", c: "if", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "وإلا", romenagri: "vaillaa", c: "else", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "طالما", romenagri: "taalamaa", c: "while", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "افعل", romenagri: "ifaela", c: "do", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "لكل", romenagri: "likulli", c: "for", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "اكسر", romenagri: "iksira", c: "break", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "استمر", romenagri: "istamirra", c: "continue", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "بدل", romenagri: "baddila", c: "switch", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "حالة", romenagri: "haalah", c: "case", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "default", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "أرجع", romenagri: "arjie", c: "return", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "ثابت", romenagri: "saabita", c: "const", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "صحيح", romenagri: "sahiiha", c: "int", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "عائم", romenagri: "aaima", c: "float", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "مزدوج", romenagri: "muzdavija", c: "double", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "حرف", romenagri: "harfa", c: "char", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "فراغ", romenagri: "faraagha", c: "void", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "دالة", romenagri: "daalah", c: "void", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "صنف", romenagri: "sanfa", c: "class", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "جديد", romenagri: "jadiida", c: "new", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "عام", romenagri: "aamma", c: "public", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "خاص", romenagri: "khaassa", c: "private", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "ساكن", romenagri: "saakina", c: "static", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "virtual", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "عندما", romenagri: "indamaa", c: "case", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "بنية", romenagri: "binyah", c: "struct", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "ضمن", romenagri: "dammina", c: "include", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "اقرأ", romenagri: "iqraa", c: "scanf", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
      { native: "اكتب", romenagri: "uktuba", c: "printf", fill: true, source: "csv:lang_punjabi_shahmukhi.csv" },
    ],
  },
  "sindhi": {
    id: "sindhi", title: "Sindhi", script: "Perso-Arabic", family: "perso", roundtrip: "lossy-abjad",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["if", "else", "while", "do", "for", "break", "continue", "switch", "case", "default", "return", "const", "int", "float", "double", "char", "void", "void", "class", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "إذا", romenagri: "izaa", c: "if", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "وإلا", romenagri: "vaillaa", c: "else", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "طالما", romenagri: "taalamaa", c: "while", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "افعل", romenagri: "ifaela", c: "do", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "لكل", romenagri: "likulli", c: "for", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "اكسر", romenagri: "iksira", c: "break", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "استمر", romenagri: "istamirra", c: "continue", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "بدل", romenagri: "baddila", c: "switch", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "حالة", romenagri: "haalah", c: "case", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "default", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "أرجع", romenagri: "arjie", c: "return", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "ثابت", romenagri: "saabita", c: "const", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "صحيح", romenagri: "sahiiha", c: "int", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "عائم", romenagri: "aaima", c: "float", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "مزدوج", romenagri: "muzdavija", c: "double", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "حرف", romenagri: "harfa", c: "char", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "فراغ", romenagri: "faraagha", c: "void", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "دالة", romenagri: "daalah", c: "void", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "صنف", romenagri: "sanfa", c: "class", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "جديد", romenagri: "jadiida", c: "new", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "عام", romenagri: "aamma", c: "public", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "خاص", romenagri: "khaassa", c: "private", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "ساكن", romenagri: "saakina", c: "static", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "افتراضي", romenagri: "iftiraadii", c: "virtual", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "عندما", romenagri: "indamaa", c: "case", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "بنية", romenagri: "binyah", c: "struct", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "ضمن", romenagri: "dammina", c: "include", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "اقرأ", romenagri: "iqraa", c: "scanf", fill: true, source: "csv:lang_sindhi.csv" },
      { native: "اكتب", romenagri: "uktuba", c: "printf", fill: true, source: "csv:lang_sindhi.csv" },
    ],
  },
  "syriac": {
    id: "syriac", title: "Syriac", script: "Syriac", family: "semitic", roundtrip: "inventory",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["for", "break", "continue", "switch", "case", "default", "const", "int", "float", "double", "char", "void", "void", "class", "new", "public", "private", "static", "virtual", "case", "struct", "include", "scanf", "printf"],
    rows: [
      { native: "ܐܢ", romenagri: "ana", c: "if", source: "tsv" },
      { native: "ܐܚܪܢܐ", romenagri: "aharanaa", c: "else", source: "tsv" },
      { native: "ܟܡܐ", romenagri: "kamaa", c: "while", source: "tsv" },
      { native: "ܥܒܕ", romenagri: "aebada", c: "do", source: "tsv" },
      { native: "עבור", romenagri: "aebuura", c: "for", fill: true, source: "hebrew-hub" },
      { native: "שבור", romenagri: "shvor", c: "break", fill: true, source: "hebrew-hub" },
      { native: "המשך", romenagri: "hemshech", c: "continue", fill: true, source: "hebrew-hub" },
      { native: "בחר", romenagri: "bchar", c: "switch", fill: true, source: "hebrew-hub" },
      { native: "מקרה", romenagri: "mikre", c: "case", fill: true, source: "hebrew-hub" },
      { native: "ברירתמחדל", romenagri: "briratmachdal", c: "default", fill: true, source: "hebrew-hub" },
      { native: "ܦܢܐ", romenagri: "panaa", c: "return", source: "tsv" },
      { native: "קבוע", romenagri: "kavuа", c: "const", fill: true, source: "hebrew-hub" },
      { native: "שלם", romenagri: "shalem", c: "int", fill: true, source: "hebrew-hub" },
      { native: "צף", romenagri: "tsaf", c: "float", fill: true, source: "hebrew-hub" },
      { native: "כפול", romenagri: "kaful", c: "double", fill: true, source: "hebrew-hub" },
      { native: "תו", romenagri: "tav", c: "char", fill: true, source: "hebrew-hub" },
      { native: "פונקציה", romenagri: "puunaqaeiyah", c: "void", fill: true, source: "hebrew-hub" },
      { native: "ריק", romenagri: "rek", c: "void", fill: true, source: "hebrew-hub" },
      { native: "מחלקה", romenagri: "mahalaqah", c: "class", fill: true, source: "hebrew-hub" },
      { native: "חדש", romenagri: "chadash", c: "new", fill: true, source: "hebrew-hub" },
      { native: "ציבורי", romenagri: "tsiburi", c: "public", fill: true, source: "hebrew-hub" },
      { native: "פרטי", romenagri: "prati", c: "private", fill: true, source: "hebrew-hub" },
      { native: "סטטי", romenagri: "stati", c: "static", fill: true, source: "hebrew-hub" },
      { native: "מדומה", romenagri: "medume", c: "virtual", fill: true, source: "hebrew-hub" },
      { native: "כאשר", romenagri: "kaasher", c: "case", fill: true, source: "hebrew-hub" },
      { native: "מבנה", romenagri: "mivne", c: "struct", fill: true, source: "hebrew-hub" },
      { native: "כלול", romenagri: "kalul", c: "include", fill: true, source: "hebrew-hub" },
      { native: "קרא", romenagri: "kra", c: "scanf", fill: true, source: "hebrew-hub" },
      { native: "כתוב", romenagri: "ktov", c: "printf", fill: true, source: "hebrew-hub" },
    ],
  },
  "tamil": {
    id: "tamil", title: "Tamil", script: "Tamil", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["include", "scanf", "printf"],
    rows: [
      { native: "எனில்", romenagri: "enila", c: "if", source: "tsv" },
      { native: "இல்லையெனில்", romenagri: "illaiyenila", c: "else", source: "tsv" },
      { native: "வரை", romenagri: "varai", c: "while", source: "tsv" },
      { native: "செய்", romenagri: "sey", c: "do", source: "tsv" },
      { native: "க்கு", romenagri: "kku", c: "for", source: "tsv" },
      { native: "நிறுத்து", romenagri: "niruttu", c: "break", source: "tsv" },
      { native: "தொடர்", romenagri: "todara", c: "continue", source: "tsv" },
      { native: "தேர்வு", romenagri: "teervu", c: "switch", source: "tsv" },
      { native: "நிலை", romenagri: "nilai", c: "case", source: "tsv" },
      { native: "இயல்பு", romenagri: "iyalpu", c: "default", source: "tsv" },
      { native: "திரும்பு", romenagri: "tirumpu", c: "return", source: "tsv" },
      { native: "மாறிலி", romenagri: "maarili", c: "const", source: "tsv" },
      { native: "முழு", romenagri: "muzu", c: "int", source: "tsv" },
      { native: "தசம", romenagri: "tasama", c: "float", source: "tsv" },
      { native: "இரட்டை", romenagri: "irattai", c: "double", source: "tsv" },
      { native: "எழுத்து", romenagri: "ezuttu", c: "char", source: "tsv" },
      { native: "வெறுமை", romenagri: "verumai", c: "void", source: "tsv" },
      { native: "செயல்", romenagri: "seyala", c: "void", source: "tsv" },
      { native: "வகுப்பு", romenagri: "vakuppu", c: "class", source: "tsv" },
      { native: "புதிய", romenagri: "putiya", c: "new", source: "tsv" },
      { native: "பொது", romenagri: "potu", c: "public", source: "tsv" },
      { native: "தனிப்பட்ட", romenagri: "tanippatta", c: "private", source: "tsv" },
      { native: "நிலையான", romenagri: "nilaiyaana", c: "static", source: "tsv" },
      { native: "மெய்நிகர்", romenagri: "meynikara", c: "virtual", source: "tsv" },
      { native: "போது", romenagri: "pootu", c: "case", source: "tsv" },
      { native: "கட்டமைப்பு", romenagri: "kattamaippu", c: "struct", source: "tsv" },
      { native: "சேர்", romenagri: "seer", c: "include", fill: true, source: "fill-literary" },
      { native: "படி", romenagri: "pa_di", c: "scanf", fill: true, source: "fill-literary" },
      { native: "எழுது", romenagri: "ezhutu", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "telugu": {
    id: "telugu", title: "Telugu", script: "Telugu", family: "brahmi", roundtrip: "lossless",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["include", "scanf", "printf"],
    rows: [
      { native: "ఒకవేళ", romenagri: "okaveela", c: "if", source: "tsv" },
      { native: "లేకపోతే", romenagri: "leekapootee", c: "else", source: "tsv" },
      { native: "వరకు", romenagri: "varaku", c: "while", source: "tsv" },
      { native: "చేయి", romenagri: "ceeyi", c: "do", source: "tsv" },
      { native: "కొరకు", romenagri: "koraku", c: "for", source: "tsv" },
      { native: "ఆపు", romenagri: "aapu", c: "break", source: "tsv" },
      { native: "కొనసాగు", romenagri: "konasaagu", c: "continue", source: "tsv" },
      { native: "ఎంపిక", romenagri: "empika", c: "switch", source: "tsv" },
      { native: "స్థితి", romenagri: "sthiti", c: "case", source: "tsv" },
      { native: "అప్రమేయ", romenagri: "aprameeya", c: "default", source: "tsv" },
      { native: "తిరిగి", romenagri: "tirigi", c: "return", source: "tsv" },
      { native: "స్థిరరాశి", romenagri: "sthiraraashi", c: "const", source: "tsv" },
      { native: "పూర్ణాంకం", romenagri: "puur_naa_nka_m", c: "int", source: "tsv" },
      { native: "దశాంశం", romenagri: "dashaa_msha_m", c: "float", source: "tsv" },
      { native: "ద్విగుణ", romenagri: "dvigu_na", c: "double", source: "tsv" },
      { native: "అక్షరం", romenagri: "ak_sara_m", c: "char", source: "tsv" },
      { native: "శూన్య", romenagri: "shuunya", c: "void", source: "tsv" },
      { native: "ప్రమేయం", romenagri: "prameeya_m", c: "void", source: "tsv" },
      { native: "తరగతి", romenagri: "taragati", c: "class", source: "tsv" },
      { native: "కొత్త", romenagri: "kotta", c: "new", source: "tsv" },
      { native: "బహిరంగ", romenagri: "bahira_nga", c: "public", source: "tsv" },
      { native: "అంతరంగ", romenagri: "a_ntara_nga", c: "private", source: "tsv" },
      { native: "స్థిర", romenagri: "sthira", c: "static", source: "tsv" },
      { native: "మాయా", romenagri: "maayaa", c: "virtual", source: "tsv" },
      { native: "ఎప్పుడు", romenagri: "eppudu", c: "case", source: "tsv" },
      { native: "నిర్మాణం", romenagri: "nirmaa_na_m", c: "struct", source: "tsv" },
      { native: "చేర్చు", romenagri: "ceercu", c: "include", fill: true, source: "fill-literary" },
      { native: "చదువు", romenagri: "caduvu", c: "scanf", fill: true, source: "fill-literary" },
      { native: "వ్రాయి", romenagri: "vraayi", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
  "urdu": {
    id: "urdu", title: "Urdu", script: "Perso-Arabic (Nastaliq)", family: "perso", roundtrip: "lossy-abjad",
    n: 29, unique_c: 27, bar: 29, complete: true, filled_c: ["scanf", "printf"],
    rows: [
      { native: "اگر", romenagri: "agara", c: "if", source: "tsv" },
      { native: "ورنہ", romenagri: "varnah", c: "else", source: "tsv" },
      { native: "جبتک", romenagri: "jabataka", c: "while", source: "tsv" },
      { native: "کرو", romenagri: "karau", c: "do", source: "tsv" },
      { native: "برائے", romenagri: "baraae", c: "for", source: "tsv" },
      { native: "توڑو", romenagri: "taudau", c: "break", source: "tsv" },
      { native: "جاری", romenagri: "jaarii", c: "continue", source: "tsv" },
      { native: "انتخاب", romenagri: "inatikhaaba", c: "switch", source: "tsv" },
      { native: "حالت", romenagri: "haalata", c: "case", source: "tsv" },
      { native: "طےشدہ", romenagri: "taeshudah", c: "default", source: "tsv" },
      { native: "واپس", romenagri: "vaapasa", c: "return", source: "tsv" },
      { native: "ثابت", romenagri: "saabita", c: "const", source: "tsv" },
      { native: "صحیح", romenagri: "sahiiha", c: "int", source: "tsv" },
      { native: "اعشاری", romenagri: "aeshaarii", c: "float", source: "tsv" },
      { native: "دوہرا", romenagri: "dauharaa", c: "double", source: "tsv" },
      { native: "حرف", romenagri: "harfa", c: "char", source: "tsv" },
      { native: "خالی", romenagri: "khaalii", c: "void", source: "tsv" },
      { native: "تابع", romenagri: "taabe", c: "void", source: "tsv" },
      { native: "جماعت", romenagri: "jamaaata", c: "class", source: "tsv" },
      { native: "نیا", romenagri: "nayaa", c: "new", source: "tsv" },
      { native: "عوامی", romenagri: "avaamii", c: "public", source: "tsv" },
      { native: "نجی", romenagri: "nijii", c: "private", source: "tsv" },
      { native: "ساکن", romenagri: "saakina", c: "static", source: "tsv" },
      { native: "مجازی", romenagri: "majaazii", c: "virtual", source: "tsv" },
      { native: "جب", romenagri: "jaba", c: "case", source: "tsv" },
      { native: "ساخت", romenagri: "saakhta", c: "struct", source: "tsv" },
      { native: "شامل", romenagri: "shaamila", c: "include", source: "tsv" },
      { native: "پڑھو", romenagri: "pa_rhau", c: "scanf", fill: true, source: "fill-literary" },
      { native: "لکھو", romenagri: "likhau", c: "printf", fill: true, source: "fill-literary" },
    ],
  },
};
export const ILM_IDS = Object.keys(ILM_LANGUAGES);
export function ilmCompleteCount() {
  return ILM_IDS.filter((id) => ILM_LANGUAGES[id].complete).length;
}
